client/app/routes/index.js
client/app/templates/index.hbs
client/tests/unit/routes/index-test.js

This PR addresses #25  by adding the template and route for the sign-in landing page:

25:  Create sign-in landing page

---

server/.gitignore
server/package.json
server/src/_utils/adal.ts
server/src/app.controller.ts
server/src/app.module.ts
server/src/app.service.ts
server/src/auth/auth.module.ts
server/src/auth/auth.service.spec.ts
server/src/auth/auth.service.ts
server/src/config/config.module.ts
server/src/config/config.service.spec.ts
server/src/config/config.service.ts
server/src/contact/contact.module.ts
server/src/contact/contact.service.spec.ts
server/src/contact/contact.service.ts
server/src/crm/crm.module.ts
server/src/crm/crm.service.spec.ts
server/src/crm/crm.service.ts
server/yarn.lock

This commit sets up a /login endpoint that takes an NYCID token,
extracts the email and uses it to look up a Contact in CRM
using the CRM Web API. It returns to the client a ZAP token holding
(signed with) the acquired Contact's contactid.
It also sets up a development scenario where by setting SKIP_AUTH=true
and providing a CRM_IMPOSTER_ID in the environment variables, on startup
the api will automatically trigger the /login endpoint with a mocked NYCID
token, and print the generated ZAP token in the console. This is useful
for bypassing the usual flow of logging in through an email.
This was adapated from existing zap-api code.
TODO: leverage oData service written by @allthesignals 
See 
* https://github.com/NYCPlanning/labs-zap-api/blob/api-only/src/odata/odata.service.ts
* …

16: Login endpoint to query for user by contactid

---

server/src/auth.middleware.ts
server/src/auth/auth.service.ts

The recently introduced middleware checked each request for a cookie with valid ZAP token. However, this does not need to happen for the initial request to the login route, which is used to acquire that ZAP token. I.e. this avoids a chicken and egg problem 🥚 🐔 ❓

Skip middleware auth for login route

---

server/src/projects/projects.controller.ts
server/src/projects/projects.service.ts

Add extra conditions to projects endpoint query -- outlined in issue #15 
**NOTE**: for primary applicant on a project I referred to `_dcp_applicantadministrator_customer_value` but there's also a `_dcp_applicant_customer_value` on dcp_project that might actually be the primary applicant field. Administrator might just refer to the person who was logged in to CRM. Need to clarify before merging

15: add statecode, statuscode, dcp_visibility conditions to projects endpoint

---

server/src/app.controller.ts

This is a small code quality improvement. The contactService.findOneById(contactId)
method should never be called if contactId is not present.

Improve code quality by preventing contactService call if no contactId present

---

.gitignore
README.md
client/.ember-cli
client/.gitignore
client/app/adapters/application.js
client/config/environment.js
client/mirage/config.js
client/package.json
client/tests/unit/adapters/application-test.js
client/yarn.lock
package.json
server/.gitignore
server/src/app.controller.ts
server/src/app.module.ts
server/src/main.ts

This PR integrates the client and the server, and adds a few necessary features for local development. To review more easily, I'd suggest going commit by commit, starting [here](https://github.com/NYCPlanning/labs-applicant-portal/pull/58/commits/db9da170ed8062dac7f97bfdc30ab3fe9e291ceb).
It enables compression, JSON:API parsing, and CORS, and allows the Ember app to accept a `HOST=` environment variable: `HOST=https://locahost:3000 yarn run start:ssl`.
You will notice that SSL and HTTPS are present! This PR enables the ability to develop locally with SSL. This is becoming more and more necessary as Chrome and others tighten restrictions on cross-origin cookies over non secure domains.
See instructions:
> # SSL Setup in Local Development
> In order for cookies to work across both the …

38 login integration

---

client/yarn.lock

Addresses #56 with a `rm -rf yarn.lock node_modules/` and a fresh `yarn install` to make sure we get the latest 1.0.7 version of the Style Guide.

56 - update yarn.lock to get newest Style Guide version

---

client/app/templates/projects.hbs

This PR improves the project template:
- Fixes the grid columns (lefthand was set to auto and righthand was set to shrink, which caused it to be way too wide)
- Changes to match aesthetics in Glitch prototype (w/ Kate's recommendations) that weren't in wireframes
- Adds the background color to the projects in righthand column
- Adds icons to each bucket header
- Hides the righthand buckets unless there's something in them. 
- Moves the breadcrumbs outside of the grid 
- Adjusts the markup to be indented by two spaces instead of 4 (@bfreeds, I assume your editor is set to 4, but we've always done 2; let's discuss this as a team)

improve the project template

---

server/src/projects/projects.service.ts

Fix minor errors in projects endpoint query -- move where we were filtering statecode for project and update statecode to statuscode for applicants.

15: fix projects endpoint query, move project statecode filtering

---

client/app/controllers/index.js
client/app/models/project.js
client/app/templates/index.hbs
client/tests/unit/controllers/index-test.js

This PR is a hot fix to have the big orange sign in button on the landing page to redirect users to nyc id.
It copies the logic used in the sign-in button in an index.js controller (left a todo to make this DRY, but wanted to get this hot fix in for demo).

Fix landing page sign-in button, redirect to nycid

---

client/netlify.toml
netlify.toml

This PR addresses #14 by adding the netlify configuration for:
- production
- staging
- qa
- develop
The `HOST` URLs referred to in this `netlify.toml` are heroku apps that have already been setup through the Heroku UI.  
Note:  Currently the Heroku develop and staging apps are both identical (didn't want to break it before the demo).

14:  Add netlify configuration

---

client/config/environment.js
netlify.toml

This PR tells the client which NYC.ID URI client ID to use when making the login the button.
Each environment needs a separate account because you have to configure each account with the correct redirect URL.
@bfreeds one thing I'm still not clear on is the difference between the `develop` branch and `staging` branch?

Map in the NYCID client IDs

---

client/.eslintrc.js
client/app/components/do-logout.hbs
client/app/components/do-logout.js
client/app/controllers/application.js
client/app/models/project.js
client/app/router.js
client/app/routes/logout.js
client/app/templates/application.hbs
client/app/templates/logout.hbs
client/config/environment.js
client/tests/acceptance/user-can-login-test.js
client/tests/integration/components/do-logout-test.js
client/tests/unit/routes/logout-test.js

This commit creates a logout route, which invalidates the local SimpleAuth session and renders a special NYC.ID logout iframe that implicitly invalidates the token they provide to the user.

Add logout component, route; migrate logic to new objects

---

client/app/authenticators/zap-api-authenticator.js
client/app/templates/projects-error.hbs
client/mirage/config.js
client/tests/acceptance/user-can-login-test.js
client/tests/acceptance/user-sees-projects-of-all-types-test.js
server/src/app.controller.ts
server/src/auth/auth.service.ts
server/src/http-exception.filter.spec.ts
server/src/http-exception.filter.ts
server/src/main.ts
server/src/projects/projects.controller.ts

This PR enforces auth by throwing an exception when `contactid` is specifically not found. Before, it was only checking if `session` was visible.
This also has the browser display error messages.

Enforce auth

---

server/yarn.lock

We were seeing errors about missing dependency 'compression'. This was fixed by deleting server/yarn.lock and running `server/yarn` again. An updated server/yarn.lock file may help.

Update server/yarn.lock to resolve dependency errors on yarn start

---

client/app/components/projects/applicant-project-card.hbs
client/app/components/projects/planning-project-card.hbs
client/app/models/project.js
client/mirage/factories/project.js
client/tests/acceptance/project-card-shows-correct-data-test.js
server/src/projects/projects.controller.ts

This PR addresses #88 by showing an "On Hold" message on a project card if the `statuscode` = "On-Hold".
Ex.

88:  Show if project is "On-Hold"

---

server/src/projects/projects.service.ts

Previously the projects endpoint only filtered associated
applicant team objects by their statuscode. This commit
ensures that projects are also in themselves filtered by whether
the authenticated contact is an "active" contact within
the project's associated applicant team members.
This filtering step was part of PR #84 /Issue #73  but
overlooked.
The critical addition to the query is the segment in bold below:
..._Project/any(o:o/_dcp_applicant_customer_value%20eq%20%27${contactId}%27
**%20and%20o/statuscode%20eq%20${applicantActiveStatusCode}** )

90 Filter out projects where contact is not in applicant team

---

client/app/controllers/login-error.js
client/app/templates/login-error.hbs
client/tests/acceptance/user-can-login-test.js
client/tests/unit/controllers/login-error-test.js
server/src/auth/auth.service.ts

I'm proposing that in Nest, we write exceptions in this format:
```
const responseBody = {
'code': 'APPLICANT_PORTAL_SPECIFIC_CODE',
'message': 'Brief details of internal error',
}
throw new HttpException(responseBody, HttpStatus.UNAUTHORIZED);
```
And the frontend can then use the `error.response.code` property (`APPLICANT_PORTAL_SPECIFIC_CODE`) to conditionally display more user friendly messages.
---
This PR modifies the frontend to display error messages for errors occuring during user login.
It also adjusts how the Applicant Portal API sends error responses to support more robust error reporting on the frontend.
In the frontend, this PR introduces an Ember error page for the login route. The error page
is automatically displayed by Ember if it detects an exception or
bad response in …

83 Handle login errors, like for missing crm contact

---

client/app/templates/projects.hbs
client/tests/acceptance/user-sees-projects-of-all-types-test.js

This commit updates the text shown when there are no applicant (To Do) projects, and also
the text for when there are no Active, Applicant-Only and General Public projects whatsoever
associated with a contact.
the applicant (To Do) projects are a subset of the Active, Applicant-Only and General Public
projects (which are any projects returned from the /projects API endpoint).
Addresses latest comments in  #87 
--- 
UI with these changes:
**No active DCP projects whatsoever:**
**No Applicant projects**
**Applicant and Planning  projects**

87 Revise text for 'no applicant projects' and 'no active dcp projects whatsoever' scenarios

---

client/app/models/pas-form.js
server/src/app.module.ts
server/src/json-api-serialize.interceptor.ts
server/src/packages/packages.controller.spec.ts
server/src/packages/packages.controller.ts
server/src/packages/packages.module.ts
server/src/packages/packages.service.spec.ts
server/src/packages/packages.service.ts
server/src/projects/projects.controller.ts
server/src/projects/projects.service.ts

This PR creates a packages service in the backend which queries for the package, its pas form, and some of the PAS form's related entities (bbls and applicantinformations).
Includes Client side changes as well.

PAS Form Packages/PASForm entity fields, etc

---

client/app/components/project-geography.hbs
client/app/components/project-geography.js
client/app/helpers/bbl-breakup.js
client/app/models/bbl.js
client/app/styles/app.scss
client/app/styles/modules/_m-search.scss
client/config/environment.js
client/mirage/config.js
client/package.json
client/tests/integration/components/project-geography-test.js
client/tests/integration/helpers/bbl-breakup-test.js
client/tests/unit/models/bbl-test.js
client/yarn.lock

This PR creates a ProjectGeography component that allows users to add bbls to their project on the PAS Form package. 
**Commit 1**: 
- Create new component ProjectGeography that represents the geography (bbls) for a specific PAS Form associated with a project. 
- This commit creates the UI for users to add or remove a specific bbl from a PAS Form. 
- This commit provides the basic UI, functionality for adding and removing bbls to an array, and an integration test that tests this functionality using mock data. 
- BBl/ project geography model has not yet been created.
**Commit 2**: 
- Add labs-ember-search addon to ProjectGeography component. Users can now search for geocoded bbls (and addresses) and add them to their list of bbls for the PAS Form. 
- Tests were updated to reflect these …

21: Add and remove BBls to PAS form through ProjectGeography component

---

client/app/components/packages/attachments.hbs
client/app/components/packages/attachments.js
client/app/models/package.js
client/app/services/file-management.js
client/app/services/file-manager.js
client/mirage/config.js
client/mirage/factories/package.js
client/package.json
client/tests/integration/components/packages/attachments-test.js
client/tests/unit/services/file-management-test.js
client/yarn.lock

Thinking of opening this up for official PR review and Merge at this state, and tackling the below Todos in future PRs. This should help avoid a massive PR down the road. 
At this stage, the component has a stable frontend UI and tests. It can
--- 
Todo/Redo for future issues:
Core feature remaining todos:

23 file upload component core frontend functionality

---

client/app/components/project-geography.hbs
client/app/components/project-geography.js

In `ProjectGeography` component: 
- Add `store.deleteRecord` to `removeBbl` action
- Standardize radio buttons
Addressing issue #21 
Following larger PR #101

21: update removeBbl action and standardize radio buttons

---

client/app/components/breadcrumbs.hbs
client/app/components/pas-form.hbs
client/app/components/pas-form.js
client/app/models/package.js
client/app/models/pas-form.js
client/app/routes/packages/edit.js
client/app/routes/projects.js
client/app/styles/app.scss
client/app/templates/application.hbs
client/app/templates/packages/edit.hbs
client/mirage/config.js
client/mirage/factories/package.js
client/mirage/models/pas-form.js
client/tests/integration/components/breadcrumbs-test.js
client/tests/integration/components/pas-form-test.js
client/tests/unit/services/file-management-test.js
client/yarn.lock

This PR addresses #18… 
(Please excuse it exceeding too many lines; the PAS form help text alone is like 500 lines.)
- Adds components for the Package Edit view
- `<Breadcrumbs>` component — currently hardcoded for Package Edit view, but can be extended for use all routes 
- `<PasForm @package={{model}} />` — conditionally rendered if the `model.dcpPackagetype` == "PAS Package"
- Stubs in PAS form elements that are not reliant on the sub-component being built — these are not functional, but get all the markup and CRM variables in place 
- Adds the "sticky" sidebar with placeholder "Save" "Submit" buttons and page navigation
Note: There are lots of `{{!--  TODO --}}` messages sprinkled throughout the code where functionality is missing that could be handled in a separate issue — e.g. the …

add pas form component

---

client/app/components/pas-form.hbs

This PR replaces the placeholder div for the applicant team editor with the actual component, rendering:
```hbs
<Packages::ApplicantTeamEditor @applicants={{@package.pasForm.applicants}}/>
```
Small part of getting #20 ready to go.

20: Use Applicant Team Editor component in PAS Form

---

client/app/components/projects/applicant-project-card.hbs
client/app/models/package.js
client/app/routes/packages/edit.js
server/src/packages/packages.controller.ts
server/src/projects/projects.controller.ts

Addresses #29, but also fixes two minor issues:
- Versionnumber wasn't being included in the data and wasn't sorting correctly
- Package edit route wasn't force-reloading

Minor bug fixes

---

client/app/templates/packages.hbs
client/app/templates/packages/edit.hbs
client/app/templates/packages/loading.hbs

This commit moves the breadcrumbs to the root of the packages route. This is needed because we want the breadcrumbs to be visible across all sub routes.
Additionally, this adds a load spinner for the packages route using the ember substate feature. This is done by adding a 'loading.hbs' template in the packages route. This route is triggered when the model is being resolved. I added this because this can be a large request, and without it, it would look like nothing is happening.

Move breadcrumbs to root; Add load spinner for packages;

---

server/package.json
server/yarn.lock

Having issues with later patches of RXJS. Pinning to 6.5.4.

Pin RXJS version

---

client/app/components/packages/pas-form/edit.hbs
client/tests/integration/components/pas-form-test.js

This PR makes the save button disabled unless the pasForm hasDirtyAttributes, and adds tests to verify behavior.
Addresses #26.

Disable save button when pas form is unchanged

---

client/app/services/file-manager.js
client/mirage/config.js
server/src/crm/crm.service.ts
server/src/document/document.controller.ts
server/src/packages/packages.controller.ts
server/src/packages/packages.service.ts

This adds a separate authentication stratgy for looking up a package’s documents in SharePoint.
That auth is used to lookup a packages uploaded documents.
Include endpoint for deleting documents.

Lookup and include package documents

---

client/app/components/packages/pas-form/edit.hbs
client/app/components/packages/pas-form/edit.js
client/app/components/reveal-modal.hbs
client/app/styles/app.scss
client/app/styles/modules/_reveal-modal.scss
client/app/templates/application.hbs
client/package.json
client/tests/integration/components/pas-form-test.js
client/yarn.lock

This PR add a `<RevealModal />` component and adjusts the UX so that the user sees a warning and must confirm submission of the PAS form. 
Addresses #86.

add confirmation modal to PAS form

---

client/app/components/packages/applicant-team-editor.js
client/app/components/project-geography.js
client/mirage/config.js

This uses the destroyRecord api instead of deleting through the store.
For reasons I don't know yet, it isn't picking up store.deleteRecord calls.

Use destroyRecord instead of store deleteRecord

---

client/app/components/land-use-action.hbs
client/app/components/packages/applicant-fieldset.hbs
client/app/components/packages/applicant-team-editor.hbs
client/app/components/packages/attachments.hbs
client/app/components/project-geography.hbs
client/app/styles/app.scss

Consistent Delete UI

---

client/app/components/packages/pas-form/show.hbs
client/app/routes/packages/show.js
client/tests/acceptance/user-can-click-package-show-test.js

This commit adds in the pas form data in a very basic way to just get it represented on the page.
Related to #161, further design on the template & reusuable ui refactoring still needed for this issue, but this gets the data on the page for QA purposes.

Add (very basic) PAS Form data to view-only page

---

client/app/components/project-geography.hbs
client/app/components/project-geography.js
client/app/models/pas-form.js
client/tests/integration/components/project-geography-test.js

**BBls list in ProjectGeography component now includes link to zola and address.** 
**Address**: When a user searches a bbl or address in the labs-search component, an object with a bbl and corresponding address is returned. A lookup is populated with these bbl-address pairs so that addresses can be displayed next to the bbl in the bbls list. NOTE: these will disappear on hard refresh. 
**Zola Link**: This PR also provides link to zola on each bbl.
Addresses #110

110: addresses next to bbl in ProjectGeography component bbl list

---

client/app/components/packages/pas-form/edit.hbs
client/app/models/pas-form.js
client/app/routes/packages/edit.js
client/tests/acceptance/user-can-click-package-show-test.js
client/tests/integration/components/pas-form-test.js
client/tests/unit/models/package-test.js

BEFORE MERGE: might cause merge conflicts in tests
Use `package.project.dcpProjectname` as a default for `package.pasForm.dcpRevisedprojectname` on the pas-form model.
Needed to update tests to account for new reference to package.project.
Addresses #119

119: pre-populate project name on pas-form with dcpProjectname

---

client/app/components/packages/pas-form/edit.js
client/tests/integration/components/pas-form-test.js

package `statuscode` is set to "Submitted" when a user clicks the Submit button on the PAS Form.
Partly addresses #27
In future PRs:
- conditions for disabling Submit button

27: package statuscode is changed to Submitted when user clicks Submit button

---

client/app/components/packages/pas-form/edit.hbs
client/app/components/packages/pas-form/edit.js
client/app/components/validation-message.hbs
client/app/validations/pas-form.js
client/package.json
client/tests/integration/components/validation-message-test.js
client/yarn.lock

This commit 
- Validates the PAS Form Text and TextArea input fields using Ember Changesets
- Disables the save button until the Changesets indicate those inputs are valid 
- On form save, persists Changeset changes to the underlying Model, which will also PATCH CRM.

174 Validations for PAS Form text input fields

---

client/app/components/packages/pas-form/edit.hbs
client/app/components/packages/pas-form/edit.js
client/app/components/radio-button.hbs
client/app/components/radio-button.js
client/app/styles/modules/_pasform.scss
client/app/templates/packages/edit.hbs
client/app/validations/saveable-pas-form.js
client/app/validations/submittable-pas-form.js
client/app/validators/required-if-selected.js
client/package.json
client/tests/integration/components/pas-form-test.js
client/tests/unit/validators/required-if-selected-test.js
client/yarn.lock
server/src/packages/packages.service.ts

Addresses #174 
Creates two sets of validations: "saveable state" and "submittable state". These are organized under the `validations` folder.
Saveable validations impose a lower requirement than submittable because they are the bare minimum required to successfully save to the server without error.
Submittable imposes higher requirements because they are the validations required for successful submission.
Based on the requirements, I've added a custom validation based on `validatePresence`. This validation only conditionally invokes validatePresence based on the value of a specified field. This is saved under the validators folder.
This PR also refactors some of the edit form to be more manageable by generating groups of radio buttons through structured data. The refactor uses …

Validate "saveable" and "submittable" forms

---

client/app/components/packages/pas-form/edit.hbs
client/app/components/packages/pas-form/edit.js
client/app/components/project-geography.hbs
client/app/components/project-geography.js
client/app/router.js
client/app/routes/packages.js
client/app/routes/projects.js
client/app/validations/submittable-pas-form.js
client/app/validators/required-if-selected.js
client/tests/acceptance/project-card-shows-correct-data-test.js
client/tests/acceptance/user-can-click-package-edit-test.js
client/tests/acceptance/user-can-click-package-show-test.js
client/tests/acceptance/user-sees-projects-of-all-types-test.js
client/tests/unit/validators/required-if-selected-test.js

Depends on #206 
Refactors the approach to multiple changes with a much simpler approach that doesn't rely on proxies, instead uses events from e-changeset. Makes conditional validations much stabler.
Refactors several template logic to simplify.
Fixes a small bug in project geographies form in which the radio groups weren't configured correctly and so changes in unrelated radio buttons would change
Authenticates routes so that an invalidated cookie will redirect users.

Dirty state touchups

---

client/app/components/packages/applicant-fieldset.hbs
client/app/components/packages/applicant-team-editor.hbs
client/app/components/packages/applicant-team-editor.js
client/app/models/applicant.js
client/mirage/factories/applicant.js
client/tests/integration/components/packages/applicant-team-editor-test.js
client/tests/unit/models/applicant-test.js
server/src/packages/pas-form/applicants/applicants.controller.ts

This PR refactors the applicants model to prep for server logic to translate frontend applicant model to the appropriate entity in CRM.  Prep work for #162.  Want to merge this as a small PR to make sure everyone has these changes in their feature branches.
The changes:
1. Rename `applicantType` to `dcpType`, to make the model consistently follow CRM naming
2. Use explicit entityType values to make it clear which entity/table in CRM they will go to.  This will make it simpler on the server side implementation.  Because this is using the explicit crm entity values, I created a computed that translates those entity names into friendly names which we use in the UI (to avoid complicated/repetitive conditionals in the template).

162:  Refactor applicants model

---

client/app/components/packages/applicant-fieldset.hbs
client/app/components/packages/applicant-team-editor.hbs
client/app/components/packages/pas-form/edit.hbs
client/app/components/project-geography.hbs
client/app/components/radio-button.hbs
client/app/components/radio-button.js
client/app/styles/modules/_pasform.scss

This PR refactors the `<RadioButton>` component to follow the style guide markup standards (labels following inputs instead of wrapping them). It also passes in the optional `@radioId` arg for the `{{radio-button-input}}` component to use — which associates the labels with their inputs.

RadioButton refactor

---

client/app/components/project-geography.js
client/app/helpers/bbl-breakup.js
client/app/models/bbl.js
client/tests/integration/components/project-geography-test.js
server/src/packages/pas-form/bbls/bbls.controller.ts

This PR adds behavior that fills out the rest of the ProjectBBL, CRM-side.
It adds lookups for mapping a borough name to a CRM-code from zap search.
needs input from @trbmcginnis

212 pas bbl validation

---

client/app/components/packages/attachments.hbs
client/app/helpers/get-env-variable.js
client/tests/integration/helpers/get-env-variable-test.js
server/src/crm/crm.service.ts
server/src/document/document.controller.ts

This PR provides handling for the get method on the /documents resource, which takes a sharepoint relative server URL, retrieves the file, and pipes it to the user.
This is not a shareable URL and may be too memory intensive but probably isn't an issue unless we expect hundreds of simultaneous downloads.
This also adds some helpers that generate deep links to CRM entities from models

View files

---

client/app/components/packages/pas-form/edit.hbs
client/app/components/packages/pas-form/edit.js
client/app/components/packages/pas-form/show.hbs
client/app/controllers/packages/edit.js
client/package.json
client/tests/acceptance/user-can-click-package-edit-test.js

A spinner is displayed on respective buttons during save or submit.
This commit also syncs the button disabled state and spinner state.
It also removes a duplicate call to pasForm.save() by calling pasForm changesets' execute() -- instead of save() --  before calling package.saveDescendents(), which will call pasForm.save() anyway. 
changeset.execute() moves the Changeset changes down to the underlying model.
For next PR: 
- disable form inputs when saving or submitting

175 Display spinners during save or submit

---

server/src/packages/packages.service.ts

This should be reverted at some point but the Sharepoint connection is failing for some unknown reasons and we need this to fail silently as we work through the issue.

Wrap Sharepoint connection with try/catch block for added resiliency

---

client/app/components/packages/pas-form/edit.hbs
client/app/components/packages/save-button.hbs
client/app/styles/app.scss

This PR adds a `<Packages::save-button />` component for the save and submit buttons, which now visually indicate to the user that the save action was successful.

Save-button component

---

client/app/components/packages/applicant-fieldset.hbs
client/tests/integration/components/packages/applicant-team-editor-test.js

This commit addresses #214, where the conditional organization input was no longer showing up.
The dcpType value changed from text (“Individual” or “Organization”) to coded values.
This commit uses the appropriate coded value to render the organization input.  It also adds a meaningful test, which would have caught when this broke previously.

214:  conditional organization applicant input

---

client/app/components/land-use-action.hbs
client/app/components/land-use-action.js
client/tests/integration/components/land-use-action-test.js
client/yarn.lock

**Bug fix**:
In the landUseAction component --> previously, when a user would enter a value into one of the action inputs (and therefore the field was set on the model), the action was added to the "existing" actions array, meanwhile it still also existed on the "new" actions array, meaning it showed up twice in the UI.
This PR filters the "new" actions array so that actions that have fields set on the model will be filtered out of that array, avoiding these actions being double counted.
**This PR also:**
- updated the property names in `allLandUseActionOptions`
- moved `allLandUseActionOptions` to be an exported constant
Addresses #235

235: update new and existing actions arrays to assure actions are not double counted

---

client/app/components/packages/attachments.hbs
client/app/components/packages/attachments.js
client/app/components/packages/pas-form/edit.js
client/app/controllers/packages/edit.js
client/app/services/file-manager.js
client/tests/acceptance/user-can-click-package-edit-test.js

This PR ...
1) Enable the Save button when files marked for upload or deletion
2) Calls fileManager.save() when the PAS Form Save button is clicked. 
fileManager.save() will execute file upload and deletion for files appropriately marked.

187 Enable Save when files marked for upload or deletion. Upload+delete files on Save. 

---

client/app/components/land-use-action.hbs
client/app/components/packages/pas-form/edit.hbs
client/app/components/project-geography.hbs

- Addresses #171 by clarifying geography instructions + adding some additional instruction improvements requested by Aline after the applicant demo (eg: telling people to use tax lot selector if they have a large project or don't have an address)
- Addresses #211 by adding a link to the signature form
- Addresses #164 by making hyperlinks open in a new tab and adding fontawesome symbol

171, 211, 164: improved instructions and hyperlinks

---

client/app/components/packages/pas-form-error.hbs
client/app/components/packages/pas-form/edit.hbs
client/app/components/packages/pas-form/edit.js
client/tests/acceptance/error-message-appears-when-save-fails-test.js
client/tests/integration/components/packages/pas-form-error-test.js

Error handling on save and submit buttons of pas-form. 
Might run into conflicts with loading spinner branch, will resolve when that's merged
Addresses #168

168: add styling, functionality, and tests for pas-form visual error handling

---

client/app/components/packages/pas-form/edit.hbs

This PR addresses #180 by preventing the submit confirmation modal from scrolling horizontally. (Also makes the cancel button same width as confirm button.)

prevent confirmation modal scrolling horz

---

client/app/components/action-form-input.hbs
client/app/components/land-use-action.hbs
client/app/components/land-use-action.js
client/mirage/factories/pas-form.js
client/tests/integration/components/land-use-action-test.js

**Feature Update:**
- Only "Zoning Authorization", "Zoning Certification", and "Zoning Special Permit" now have a count field input. When an action is added from the dropdown, its count field is automatically set to 1. Addresses #245 
**Refactor:**
- Create a new array `actionsAddedByUser` that acts as a reference array for distinguishing new actions that the user has selected from the dropdown.
- Redefine `selectedActions` by filtering by actions that have values set on the model OR exist in `actionsAddedByUser` array. By avoiding combining two different arrays (one "new" and one "existing"), and instead just filtering ONE array we can simplify this computed property and avoid double counting actions that might meet both criteria.
**Sorting:**
- Add sorting logic. Actions should be …

245 revise land use action component

---

client/app/components/packages/applicant-fieldset.hbs
client/app/components/packages/applicant-team-editor.hbs
client/app/components/packages/pas-form/edit.hbs
client/app/components/project-geography.hbs
client/app/models/applicant.js
client/app/styles/app.scss
client/app/styles/modules/_pasform.scss
client/tests/integration/components/packages/applicant-team-editor-test.js

This PR improves the PAS form, fixing some invalid syntax (paragraphs within labels), using `.help-text` and `.text-small` more semantically, moves the Tax Lot Selector note/link to a more appropriate place in the layout (not inside the `fieldset-adder`, and makes the language more consistent in the Team section (using "Other" instead of "Representative").

improve PASForm markup

---

client/app/components/packages/applicant-fieldset.hbs
client/app/components/packages/applicant-fieldset.js
client/app/models/applicant.js
client/tests/integration/components/packages/applicant-team-editor-test.js

Since the applicant dcpState field is an option set, we
introduce a dropdown for that field so for users can search and
select for a specific state. In the frontend business logic,
we translate the selected state into its respective option set
code and assign the code to the applicant.dcpState field.
Addresses #183 and #210

183 Patch applicant geographic state

---

client/app/components/packages/pas-form/edit.hbs

Pass in `this.saveableChanges` instead of `this.pasForm` when render landUseAction component in edit.hbs
addresses #271

271: save button on PAS form triggers enabling of save button

---

client/app/components/packages/pas-form/edit.hbs
client/app/components/packages/pas-form/edit.js
client/app/components/packages/save-button.hbs
client/app/components/packages/save-button.js
client/app/models/package.js
client/tests/unit/models/project-test.js

This refactors parts of the pas-form and most of the save-button to be a little more generic, know a little less about each other.
This simplifies the save-button public API surface, encapsulates some of the button-specific state that pas-form was taking care.
Validations are injectable now, moving the pas-form component to something a little more generic, but not yet.

Make generic save button; make more generic pas-form

---

client/app/components/saveable-form.hbs
client/app/components/saveable-form.js
client/app/components/saveable-form/input.js
client/tests/integration/components/saveable-form-test.js

Extracts some general behavior from pas-form/edit so we can re-use that functionality in other types of forms.
```handlebars
<SaveableForm
@model={{this.dummyModel}}
@submit={{this.doSubmit}}
as |saveable-form|
>
<saveable-form.radio
@groupValue={{this.saveableChanges.someAttribute}}
/>
<saveable-form.submitButton
@isEnabled={{not this.model.isDirty}}
/>
</SaveableForm>
```

Create SaveableForm component

---

client/app/components/packages/pas-form/edit.hbs
client/app/validations/saveable-pas-form.js
client/app/validations/submittable-pas-form.js

Fixes validation messages not showing up for Text Input and TextArea fields.
Does so by removing maxlength attributes. This addresses Issue #231.
Later, we can add character count display to improve user experience.
This commit also:
- adds a 'min' attribute to validateLength validators so
their error messages do not show an undefined variable.
- Displays validation messages in the UI from both
saveableChangeset and submittableChangeset
next to respective fields.

231 Display Text Input validation messages

---

client/app/components/action-form-input.hbs
client/app/components/land-use-action.hbs
client/app/components/land-use-action.js
client/app/components/packages/pas-form/edit.hbs
client/app/components/validation-message.hbs
client/app/validations/saveable-pas-form.js
client/app/validations/submittable-pas-form.js
client/app/validators/validate-number-if.js
client/tests/acceptance/land-use-action-fields-validate-test.js
client/tests/integration/components/land-use-action-test.js

Validate land use action fields for `save`:
- length of fields for land use actions
Validate land use action fields for `submit`:
- Zoning Special Permit, Zoning Certification, and Zoning Authorization count field should be greater than or equal to 1 (creation of a new `validateNumberIf` function for Zoning Authorization, Zoning Certification, and Zoning Special Permit)
- if count field for action exists, assure extra questions are answered
- update `validatePresenceIf` to allow for `!==`. This was necessary for checking whether one of the three zoning fields above were not `null` or `undefined` (if a user has selected one of these options from the dropdown menu, the count field will NOT be null or undefined, but a number or an empty string. We don't want validation to happen if a user …

197: validate land use action fields for save and submit

---

client/mirage/factories/applicant.js
server/src/packages/packages.controller.ts
server/src/packages/packages.service.ts
server/src/packages/pas-form/applicants/applicants.controller.ts

This PR addresses #238 and addresses #240, by adding conditional logic to our api server for handling applicants.  
Previously all applicants being added in applicant portal would go to the `Applicant Information` grid in CRM, and would not bring in existing `Applicant Representative Information` records.  
This fixes by:
- Including the representative entity in the packages controller (for getting existing applicant representatives)
- Gives the frontend an attribute `target_entity` so the app knows what kind of applicant to render
- Conditionally Posts/Patches/Deletes the appropriate CRM entity through conditional logic in the applicant controller.

240:  Route applicants to the correct CRM entity/table

---

client/app/components/packages/pas-form/edit.hbs

This PR improves the headers on PAS form — adding an `<h1>` so it's clear what form you are editing, increasing the visual hierarchy, and visually separating the intro text from the first form section.

PAS form headers

---

client/app/components/packages/attachments.hbs
client/app/components/packages/pas-form/edit.hbs
client/app/models/package.js
client/app/routes/packages.js
client/tests/acceptance/user-can-click-package-edit-test.js
client/tests/integration/components/packages/attachments-test.js
client/tests/unit/models/package-test.js

Changes how filemanger is instantiated on the package model. This is called manually now instead from the deprecated ready hook.
Includes a test cause simulating the server response.

Refactor how filemanager is invoked; add test case

---

client/app/models/pas-form.js
server/.eslintrc.js
server/src/packages/packages.controller.ts
server/src/packages/packages.service.ts

This makes changes to the backend to set the pas form 'revised project name' to the associated _project's_ name if it's empty.

Sets dcp_revisedprojectname to projectname if empty

---

client/app/components/packages/pas-form/edit.hbs
client/app/validations/saveable-pas-form.js
client/app/validations/submittable-pas-form.js
client/tests/acceptance/user-can-click-package-edit-test.js

This commit spreads saveable changeset properties
into their respective submittable changeset properties,
preventing them from being overriden. With this patch,
we no longer need to render a ValidationMessage component
for both saveable and submittable errors. We just need
to render one for the submittable changeset errors, since
it will also contain saveable changeset errors.
This commit also fixes a few test selector names
for consistency. The test selectors for two text input
fields (dcpprojectareaindutrialzonename, dcpUrbanareaname)
were referring to non-existant, ad hoc fields.
The test selector for dcpprojectarealandmarkname ValidationMessage
was referring to the related yes/no question,
instead of the text input itself.

Properly extend submittable from saveable changeset

---

client/app/components/packages/pas-form/edit.hbs
client/app/components/packages/pas-form/show.hbs
client/tests/acceptance/error-message-appears-when-save-fails-test.js
client/tests/acceptance/user-can-click-package-edit-test.js

Update all (and add a couple) test selectors that conform to the pattern
```
data-test-[element or form input type]="<dcpModelpropertyname>"
```
Radio inputs follow this pattern:
```
data-test-radio="<dcpModelpropertyname>"
data-test-radio-option="<model property value>"
```
Note that `<dcpModelpropertyname>` represents the CRM-defined property name. We keep CRM's capitalization pattern.
Examples:
```
<Input
@type="text"
@value={{saveable-form.saveableChanges.dcpProposeddevelopmentsiteotherexplanation}}
data-test-input="dcpProposeddevelopmentsiteotherexplanation"
/>
```
```
<Input
@type="checkbox"
....
data-test-checkbox="dcpProposeddevelopmentsitenewconstruction"
/>
```
```
<saveable-form.radio
@value={{radio.code}}
@groupValue={{saveable-form.saveableChanges.dcpHousingunittype}} …
```

326 consistent test selectors

---

client/app/styles/app.scss
client/app/styles/modules/_powerselect-overrides.scss

(too short, rounded corners, wrong border color)
(matches input height, square corners, matching border color)

add CSS overrides so Ember Power Select matches our styles

---

client/app/components/packages/pas-form/show.hbs

This PR fixes some bad copy/paste which broke the display of "Funding source" in the PAS show template. Addresses #335.

fix PAS show funding source var

---

client/app/components/land-use-action.hbs
client/app/components/packages/pas-form/edit.hbs
client/app/components/validation-message.hbs
client/app/validations/saveable-pas-form.js
client/app/validations/submittable-pas-form.js
client/tests/acceptance/land-use-action-fields-validate-test.js
client/tests/acceptance/pas-form-validation-messages-display-test.js
client/tests/acceptance/user-can-click-package-edit-test.js
client/tests/helpers/exceed-maximum-characters.js

This PR:
- Adds acceptance test to account for ALL validations that occur on the PAS form (although land use actions have their own acceptance test) so that we have them all in one place. Because checking the required validations can be tedious, this test is meant to capture all validations that QA has been checking for and to make sure we have generic tests for when we conduct future refactors of the form (e.g. separating out components). This file can also function as extra documentation. 
- Standardize validation messages on text length
- Adds requirement for `dcpRevisedprojectname` to exist before submitting
Addresses #252 
Also addresses #317 (`dcpProjectattachmentsotherinformation` character counter is now consistent with its maximum length of `2000`)

252: Standardize and add test for PAS form validation

---

client/app/components/packages/applicant-team-editor.hbs
client/app/components/packages/applicant-team-editor.js
client/app/components/saveable-form.js
client/tests/acceptance/pas-form-validation-messages-display-test.js
client/tests/acceptance/user-can-click-package-edit-test.js
client/tests/integration/components/packages/applicant-team-editor-test.js

This PR addresses #307.
Previously, if the applicants array was empty we were adding a blank applicant record so we could render an empty applicant fieldset for the user.   This commit removes that to simplify UX and DX.
When a user clicked “Remove Applicant” button, we were using model.destroyRecord(), which would immediately send a DELETE request to the api server.
In this commit, we use model.deleteRecord() instead, which sets model.isDeleted = true.  This queues the record for deletion when the user clicks “Save” (which ultimately will trigger model.save(), where Ember Data makes the api reqeust to DELETE.

307:  Update add and remove applicant state management

---

client/app/components/packages/pas-form/edit.hbs
client/tests/acceptance/user-can-click-package-edit-test.js

When a user enters text into a conditional input (which only displays when the associated radio button is set to Yes or checkbox is `checked`), then clicks the No radio button or the checkbox again -- the text value is reset to empty string or null, so that text is not saved to the model.
Setting a conditional `@value` on the input (through an inline `if` statement) did not work. So instead, an action was defined on the radio buttons (`@checked`) and on the checkboxes (`click`) to set the targeted input value to an empty string or null anytime that the radio button/checkbox was selected.
Addresses #293

293: reset conditional input value when radio button set to no

---

client/app/components/land-use-action.hbs
client/app/components/packages/applicant-team-editor.hbs
client/app/components/packages/attachments.hbs
client/app/components/project-geography.hbs
client/app/modifiers/animate-with.js
client/app/styles/app.scss
client/app/styles/modules/_transitions.scss
client/package.json
client/tests/integration/modifiers/animate-with-test.js
client/yarn.lock

This PR adds CSS-only animations that make it clear to the user that an element has been inserted into the DOM — specifically, adding Team Members, BBLs, Land Use Actions, and Attachments.

Ac custom transitions

---

client/app/components/packages/pas-form/edit.hbs

Addresses #356 
Adds the "Unsure at this time" radio option for the PAS Form question
"Does the proposed development involve discretionary funding for Affordable Housing Units?"

356 Add unsure option for dcpDiscressionaryfundingforffordablehousing

---

client/app/components/packages/pas-form/edit.hbs

Addresses #331 
The CRM optionset codes for "Yes" and "No" for the field dcpRestrictivedeclarationrequired
are reversed, compared to other PAS Form fields. Here, we work around this inconsistency
by reversing the codes in the frontend. Ideally, however, we should consider making this
change in CRM instead.
For `dcpRestrictivedeclarationrequired`...
Yes - 717170001 
No - 717170000
While for other fields like `dcpProjectareaischancefloodplain`...
Yes - 717170000
No - 717170001

331 Switch values for dcpRestrictivedeclarationrequired to match CRM optionset

---

server/src/crm/crm.service.ts

The Sharepoint REST API requires special formatting of
any folder paths passed as arguments. Here we escape
apostrophes in the folder path. Otherwise, Packages
with apostrophes in their name causes an error upon
requesting their associated documents.

Encode and escape Sharepoint folder paths

---

server/src/document/document.controller.ts
server/src/packages/packages.service.ts

This commit updates the document upload and retrieval
sections of the backend (document controller and package
service, respectively) to reference Sharepoint document
folders created automatically by the package revision loop.
Those folders use a slightly different naming convention than
the default folders used previously.
Package Revision folders:
```
<formatted package name>_<unformatted package id>
```
Previous/default Package folders:
```
<unformatted package name>_<formatted package id>
```
As long as the client+server uploads and retrieves documents to
packages starting from the very first revision,
any given package revision folder will hold all documents uploaded
to the revision itself and all previous revisions. This is because
CRM automatically carries over documents from …

311 Use revision sharepoint folder for documents

---

client/app/components/packages/pas-form-error.hbs
client/app/components/packages/pas-form/edit.hbs
client/app/components/packages/pas-form/edit.js
client/app/models/package.js
client/app/services/file-manager.js
client/tests/acceptance/error-message-appears-when-save-fails-test.js

Previously, because `existingFiles` is only loaded once when the fileManager is instantiated, the `existingFiles` array was not being updated (and therefore not displaying) the recently uploaded files after the user had clicked save. They would only display when a user refreshed. This PR assures that the uploaded file objects are pushed to the `existingFiles` array so that they show in the UI. 
`pas-form-error` component was also updated to account for package errors, since `documents` exist as an attribute on the package model rather than the PAS Form model.
Closes #290

290: assure that uploaded files show up in existing files list after save

---

client/app/components/packages/pas-form/show.hbs
client/app/models/pas-form.js
client/app/models/project-address.js
client/app/routes/packages.js
client/tests/integration/components/packages/pas-form/show-test.js
server/src/packages/packages.controller.ts
server/src/packages/packages.service.ts

This PR sideloads the Project Address entity along with Pas Forms, and lists
Project Addresses on the Pas Form "Show" page.
Details: 
BBL addresses are created automatically by CRM each time
a BBL is added. They are stored on a separate entity called Project Address.
Project Address has a many to one relationship to Pas Form. We
create this relationship on the Pas Form model to Project
Address and load this property from the backend.
On the show Pas Form page, we list each validated address
separetely from the BBLs list.

339 list street addresses on pas form show page

---

client/app/components/character-counter.hbs
client/app/components/packages/rwcds-form/edit.hbs
client/app/components/packages/rwcds-form/edit.js
client/app/components/packages/rwcds-form/project-description.hbs
client/app/components/text-area.hbs
client/app/components/text-input.hbs
client/app/helpers/optionset.js
client/app/models/rwcds-form.js
client/app/validations/saveable-pas-form.js
client/app/validations/saveable-rwcds-form.js
client/app/validations/submittable-rwcds-form.js
client/tests/acceptance/user-can-click-rwcds-form-edit-test.js
client/tests/integration/components/character-counter-test.js
client/tests/integration/components/packages/rwcds-form/project-description-test.js

This is a two part/commit PR. It wraps the RwcdsForm::Edit component within the SaveableForm, then wires up the inputs for the Project Description section.
--- 
In addition to wrapping the RwcdsForm::Edit component template
inside the SaveableForm component, this commit introduces
validations and changesets for ProjectDescription to start off.
The SaveableForm component requires validations in order to
automatically generate Saveaable and Submittable changesets.
- Wires up the inputs for the Project Description section
(It does not yet prefill the inputs based on a PAS Form)
- Fixes the showCounter argument on TextArea and TextInput
- Patches CharacterCounter to always display

222 Add RWCDS Project Description section

---

client/app/components/breadcrumbs-item.hbs
client/app/components/breadcrumbs.hbs
client/app/components/breadcrumbs.js
client/app/templates/pas-form.hbs
client/app/templates/pas-form/edit.hbs
client/app/templates/pas-form/loading.hbs
client/app/templates/pas-form/show.hbs
client/app/templates/projects-error.hbs
client/app/templates/projects-loading.hbs
client/app/templates/projects.hbs
client/app/templates/rwcds-form.hbs
client/app/templates/rwcds-form/edit.hbs
client/tests/integration/components/breadcrumbs-item-test.js
client/tests/integration/components/breadcrumbs-test.js

This PR refactors the breadcrumbs so that they'll work with any routes or model. 
Previously, we had the breadcrumbs hardcoded in the projects template, and used a component that only worked for the PAS form. 
The proposed changes allow the `<Breadcrumbs />` component to be call from any template with a contextual component used for its list items. This lets us nix `breadcrumbs.js`, as we no longer rely on the router service for comparing the current route. This also adds breadcrumbs to the appropriate templates, and adds tests to make sure we render breadcrumbs correctly. 
Other methods explored (brainstormed w/ @godfreyyeung): 
- We attempted to simply pass the model to `<Breadcrumbs />` and let the component create the list items. However, this involved complex logic to dynamically …

Ac breadcrumbs

---

server/src/packages/packages.module.ts
server/src/packages/rwcds-form/rwcds-form.controller.spec.ts
server/src/packages/rwcds-form/rwcds-form.controller.ts
server/src/packages/rwcds-form/rwcds-form.service.spec.ts
server/src/packages/rwcds-form/rwcds-form.service.ts

There are two alternatives to this implementation, see below. I explored alternative 1 but got stuck modifying the JSON API Serializer. 
Adds a new RWCDS Service in the backend in charge of updating
the RWCDS Form. While patching the RWCDS Form, it also copies
the RWCDS buildyear property over to the associated Project's
anticipatedyearbuilt property.
The service first needs to acquire the form's projectid through
a network request for the associated package. This is because
projectid information doesn't come from the frontend.
1. Create a relationship between Forms (RWCDS, PAS) and Projects in the frontend, so that that when PATCHing a form, the request payload can include the Project Id. This will avoid a double network request within the RWCDS Patch. 
2. Create a separate endpoint …

222 Write to project dcp_anticipatedyearbuilt

---

client/app/components/land-use-action.hbs
client/app/components/packages/applicant-fieldset.hbs
client/app/components/packages/attachments.hbs
client/app/components/packages/pas-form/project-area.hbs
client/app/components/packages/pas-form/project-description.hbs
client/app/components/packages/pas-form/project-geography.hbs
client/app/components/packages/pas-form/project-information.hbs
client/app/components/packages/pas-form/proposed-development-site.hbs
client/app/components/project-geography.hbs
client/app/components/ui/fieldset.hbs
client/app/components/ui/label-text.hbs
client/app/components/ui/question.hbs
client/tests/acceptance/user-can-click-pas-form-edit-test.js
client/tests/integration/components/ui/fieldset-legend-test.js
client/tests/integration/components/ui/label-text-test.js
client/tests/integration/components/ui/question-test.js

This PR refactors the `<Ui::Fieldset>` component so that it works for all form questions (including text inputs and textareas, which need to be wrapped in a `<label>` instead of a `<fieldset>`). 
The new API is: 
```
<Ui::Question [@group={{true}}] as |Q|>
<Q.prompt>
</Q.prompt>
...
</Ui::Question>
```
If you pass the optional `@group={{true}}`, the component will render a `<fieldset>` element instead of the default `<label>` element, and call the `Ui::label-text` component instead of the default `Ui::FieldsetLegend` component.
This PR also 
- Changes the validation message classes to follow the style guide
- Nixes some unnecessary CSS

Ui::Question component

---

client/app/components/packages/rwcds-form/project-description.hbs
client/app/models/rwcds-form.js

For RWCDS form `dcp_constructionphasing` field (i.e. "Will construction be done in multiple phases?" question), add the NULL option. The label is displayed as "Not Applicable".

222 Add null/NA option to dcpConstructionphasing

---

client/app/components/packages/rwcds-form/attached-documents.hbs
client/app/components/packages/rwcds-form/edit.hbs
client/app/components/packages/rwcds-form/edit.js
client/app/components/ui/download-link.hbs

Creates an attached-documents component for RWCDS form, similar to the one for PAS form. Creates an "download link" component, which is similar to the "external link" component, to support the attached-documents text.

234 Add Attached Documents section for RWCDS Form

---

server/src/packages/pas-form/pas-form.service.ts
server/src/packages/rwcds-form/rwcds-form.service.ts

The expand statements caused returned RWCDS form and PAS forms to have packages nested within them. However, package info is already included adjacent to the RWCDS form and PAS forms. Also, the JSON API Serializer ignores the nested package information.

Removes unnecessary expand statements. Fix comments

---

client/app/components/packages/pas-form/attached-documents.hbs

Changed the Official Zoning Map link to 
https://www1.nyc.gov/site/planning/zoning/index-map.page

Updated the "Official Zoning Map" hyperlink

---

client/app/components/packages/pas-form/show.hbs
client/app/components/packages/rwcds-form/show.hbs
client/app/components/ui/answer-field.hbs
client/app/components/ui/answer-prompt.hbs
client/app/components/ui/answer.hbs
client/app/helpers/optionset.js
client/app/models/pas-form.js
client/app/routes/rwcds-form/edit.js
client/app/templates/rwcds-form/show.hbs
client/tests/integration/components/ui/answer-field-test.js
client/tests/integration/components/ui/answer-prompt-test.js
client/tests/integration/components/ui/answer-test.js

This PR…
- Add the RWCDS show route and template
- Adds a `<Ui:Answer>` component that reduces the repetition and brittle markup of the PAS and RWCDS show routes — which works much like the `<Ui:Question>` component for the edit routes
```
<Ui::Answer [@beside={{true}}] as |A|>
<A.Prompt>
...
</A.Prompt>
<A.Field>
...
</A.Field>
</Ui::Answer>
```
(Passing the optional `@beside={{true}}` will put the prompt and field in a grid so that they're beside each other. Without it, the prompt appears above the filed.) 
- Updates the `{{optionset}}` helper so that it can be passed falsey args
NOTE: Still need to get the list of actions and attachments in the RWCDS show template

RWCDS show route and template

---

client/app/components/packages/attachments.hbs

This PR fixes some bad markup in the attachments component. 
- Call prompt poperly w/ `@fieldset={{true}}` — this was causing the whole component to be wrapped in a `<label>` tag
- Remove `.site-main.grid-x.grid-margin-x` class
- Remove unnecessary grid cells
- Only show hr if there's content to separate

improve markup in attachments component

---

server/src/packages/rwcds-form/affected-zoning-resolution/affected-zoning-resolution.controller.ts
server/src/packages/rwcds-form/affected-zoning-resolution/affected-zoning-resolutions.attrs.ts
server/src/packages/rwcds-form/affected-zoning-resolution/affected-zoning-resolutions.controller.spec.ts
server/src/packages/rwcds-form/affected-zoning-resolution/affected-zoning-resolutions.controller.ts
server/src/packages/rwcds-form/rwcds-form.service.ts

- set up backend patch for updating `dcp_affectedzoningresolution` entity
- when rwcds' `find` method is run, a new method `syncActions` will copy `dcp_projectaction` entity associated with current project to `dcp_affectedzoningresolution`. The frontend then only interacts with `dcp_affectedzoningresolution`
Addreses issue #223 (reference this issue for scope of problem).

223 create syncactions method for proposed actions

---

client/app/components/packages/applicant-fieldset.hbs
client/app/components/packages/land-use-action.hbs
client/app/components/packages/pas-form/project-area.hbs
client/app/components/packages/pas-form/project-information.hbs
client/app/components/packages/pas-form/proposed-development-site.hbs
client/app/components/packages/rwcds-form/project-description.hbs
client/app/components/packages/rwcds-form/proposed-project-actions.hbs
client/app/components/packages/rwcds-form/with-action-no-action.hbs
client/app/components/ui/required-asterisk.hbs

This PR adds a `<Ui::RequiredAsterisk />` component which is called within prompts to indicate that its field is required. 
```
<Ui::Question as |Q|>
<Q.Prompt>
What's your name?
<Ui::RequiredAsterisk />
</Q.Prompt>
...
</Ui::Question>
```
It inserts a FontAwesome asterisk icon with a tooltip. 
-----
NOTE: As is, the `<Ui::Question>` component is not aware of the `<Form.Field>` and this PR is more evidence that they could be refactored as one component that generates both the prompt and the field(s), auto generating `for=""` attributes. We're already flagging in the "saveable" validations which fields are required, and this PR flags the labels separately. It would be nice if we could easily keep the prompt asterisk in sync with the validation.

add RequiredAsterisk component and call it in prompts

---

client/app/components/packages/pas-form/show.hbs

Addresses #335. The Urban Renewal Area name `dcpUrbanareaname` was missing in the pas/show template.

335: include ura name on pas how template

---

client/app/components/packages/rwcds-form/project-description.hbs
client/tests/acceptance/user-can-click-rwcds-form-edit-test.js

Also update copy based on updates to wireframe
Addresses #479  
The issue was not that the input for `dcpSitehistory` was missing. It was that it was accidentally associated with the question for build year rational, and there was no input for `dcpRationalbehindthebuildyear`

479 Add field for build year rational

---

client/app/components/packages/pas-form/show.hbs

Display the applicant state label instead of code
on the view-only page.

341 use optionset helper to display applicant state

---

client/app/components/packages/rwcds-form/proposed-project-actions-editor.hbs
client/app/components/packages/rwcds-form/proposed-project-actions-editor.js
client/app/helpers/optionset.js
client/app/models/affected-zoning-resolution.js
server/src/packages/packages.controller.ts
server/src/packages/packages.module.ts
server/src/packages/rwcds-form/affected-zoning-resolution/affected-zoning-resolutions.attrs.ts
server/src/packages/rwcds-form/affected-zoning-resolution/affected-zoning-resolutions.controller.ts
server/src/packages/rwcds-form/rwcds-form.service.ts

Fixing the backend/frontend synchronization of proposed actions. 
- Provide optionset in frontend to convert codes to zoning resolution labels
- updating component logic in `proposed-project-action-editor.js` in order to better display relevant info on template
- update backend field mapping to accurately reflect the relevant attributes. This included expanding on `dcp_projectaction` entity to grab `dcp_ZoningResolution.dcp_zoningresolution` which maps to `dcp_zrsectionnumber` on `dcp_affectedzoningresolution` entity
- update logic for which rows we post from `dcp_projectaction` to `dcp_affectedzoningresolution` -- there were a couple bugs in this approach, so this was refactored
Addresses #480

480: update backend for proposed actions

---

client/app/components/saveable-form/field.hbs
client/app/components/saveable-form/field/text-input.hbs

Render Character Counter for just text input and
text area fields. Ensure that the maxlength
property is passed to the text input/area fields.
Addresses #500

500 Fix character counter rendering

---

client/app/components/packages/rwcds-form/edit.js
client/app/helpers/optionset.js
client/app/models/rwcds-form.js
client/tests/acceptance/user-can-click-rwcds-form-edit-test.js

Add `submitPackage` action to rwcds-form edit.js so that it is accessible in the template.
Add optionsets to rwcds-form for use on show page.
Addresses #499

499: fix submit on rwcds form

---

client/app/components/packages/applicant-fieldset.hbs
client/app/components/packages/land-use-action.hbs
client/app/components/packages/pas-form/applicant-team.hbs
client/app/components/packages/pas-form/edit.hbs
client/app/components/packages/pas-form/project-area.hbs
client/app/components/packages/pas-form/project-description.hbs
client/app/components/packages/pas-form/project-geography.hbs
client/app/components/packages/pas-form/project-information.hbs
client/app/components/packages/pas-form/proposed-development-site.hbs
client/app/components/packages/pas-form/proposed-land-use-actions.hbs
client/app/components/packages/project-geography.hbs
client/app/components/packages/rwcds-form/proposed-project-actions.hbs

Addresses #504 
- Commit 1: clarifies which variable refers to the form, which to the model.
It also is consistent with rwcds-form/edit.hbs
- Commit 2: use lowercase form block params to indicate a form hash/object
Change to |form| (lowercase form) to follow community conventions.
This conveys that the variable represents the SaveableForm yielded
hash, instead of a rendered component.

504 rename the pasForm block param to saveableForm

---

client/app/components/packages/rwcds-form/edit.hbs
client/app/models/package.js
client/app/models/rwcds-form.js
client/tests/acceptance/user-can-click-rwcds-form-edit-test.js

Update save action on rwcds form to include affected-zoning-resolution model.
Update enable/disabled save button functionality to include dirty attributes for affected-zoning-resolution model.
Addresses #509

509: fix save button on rwcds form to save nested model affected-zoning-resolutions

---

client/app/components/saveable-form/field/text-area.hbs
client/tests/acceptance/error-message-appears-when-save-fails-test.js
client/tests/acceptance/pas-form-validation-messages-display-test.js
client/tests/acceptance/user-can-click-rwcds-form-edit-test.js

🧹🧹🧹 
Previously, we had two different test selectors, data-test-textinput
and data-test-textarea, for single-line inputs and text areas respectively.
However the new Field component assigns data-test-input as the selector
for all input types, even radio inputs. Thus we no longer need
data-test-textarea selectors on text areas. In fact, prior to this
commit, text areas had both data-test-textarea and data-test-input
selectors attached to the element.

Remove legacy use of data-test-textarea

---

client/app/components/packages/pas-form/pas-form-error.hbs
client/app/components/packages/rwcds-form/rwcds-form-error.hbs
client/tests/acceptance/error-message-appears-when-save-fails-test.js

In the PAS Form and RWCDS Form adapter error components,
display the default status and message propoerties for each
error. Also iterate through and list properties nested
within the erorr.response property.
Addresses #490  
We still need to unify the two adapter error components, which is captured in Issue #515

490 Display default and nested props in error resp

---

client/app/helpers/optionset.js
client/app/models/project.js
client/app/optionset-lookups/project-optionset-lookup.js
server/src/projects/projects.attrs.ts

- Add `dcp_publicstatus` as new attribute on projects endpoint in server.
- Add `dcp_publicstatus` to frontend model
- Add a new optionset lookup
**NOTE**: fixing weird linting error and then will mark ready for review
Addresses #470

470: add dcp_publicstatus as new attribute on projects endpoint

---

server/src/packages/pas-form/pas-form.service.ts

Although the default behavior of CRM for 0 related entities is to return a blank array, this isn’t true for a single related entity (a has one). If there is no association, it returns null.
This fix accounts for that.

Include default object for destructuring

---

client/app/components/packages/pas-form/applicant-team.hbs
client/app/components/packages/pas-form/project-area.hbs
client/app/components/packages/pas-form/project-geography.hbs
client/app/components/packages/pas-form/proposed-development-site.hbs
client/app/components/packages/pas-form/proposed-land-use-actions.hbs
client/app/components/packages/project-geography.hbs
client/app/components/packages/rwcds-form/proposed-project-actions-editor.hbs
client/app/components/packages/rwcds-form/proposed-project-actions-editor.js
client/app/components/packages/rwcds-form/proposed-project-actions.hbs
client/app/components/packages/rwcds-form/with-action-no-action.hbs
client/app/components/saveable-form/index.hbs
client/tests/integration/components/saveable-form-test.js

Changes to a more generic name that conceals the distinction between "saveableChanges" and "submittable".
Mergable after https://github.com/NYCPlanning/labs-applicant-portal/pull/530
For immediate review, look at this diff https://github.com/NYCPlanning/labs-applicant-portal/pull/532/commits/d9584463b3fc617b6c9fe81844c8677249268b6d

Update saveable changes to data

---

client/app/components/packages/rwcds-form/proposed-project-actions.hbs

Update "which actions from other agencies are sought" question on rwcds form to "text-area" to since users are able to type in 2400 characters. This update fixed the validation message and character counter error.

548: update which actions question on rwcds form to include validation message/counter, update to text-area

---

client/app/components/packages/rwcds-form/edit.hbs

Remove unnecessary "v" in project name on rwcds form

544: remove v in project name on rwcds form

---

client/app/controllers/projects.js
client/app/models/project.js

**Problem 1:**
- Previously, `pasPackages` on the project model was only returning the first package in the array (which represented the most recent version). 
- This PR separates out `pasPackages` computed property and `latestPasPackage` computed property so that we have access to all the package versions in an array as well as the most recent one. 
- This was necessary for displaying ALL versions of a package on the project.hbs template.
**Problem 2:**
- the filtering logic for `done` vs `todo` projects was pulled out of the `todo` and `done` computed properties on the projects.js controller and placed in an exported function at the top of the file.
- This not only simplifies the logic but also fixes faulty display logic that was causing projects to end up in both columns rather than …

542: update logic for frontend package versioning

---

client/app/templates/projects-error.hbs

Short and sweet PR to list errors on the Projects page just like how we decided to do so on the PAS and RWCDS form pages, and login page. 
We should also do this for `projects/id`, and work to componentize this code. Perhaps we can do so in #515

526 List errors on projects page like for forms

---

client/package.json
client/yarn.lock

This simple PR updates Labs UI to the latest patch version which loads the NYC Planning logo from addon instead of from raw.githubusercontent.

Update Labs UI

---

client/app/components/packages/rwcds-form/proposed-project-actions-editor.hbs
client/app/components/packages/rwcds-form/proposed-project-actions-editor.js
server/src/packages/rwcds-form/rwcds-form.service.ts

- this PR sets `dcp_includezoningtextamendment` on the rwcds-form to "Yes" (`717170000`) if there exists a "ZR" action and that action's `dcp_ZoningResolution.dcp_zoningresolution` attribute is equal to "AppendixF". 
- This update occurs every time the `syncActions` function is run in `rwcds-form.service.ts`, which means it runs every time the rwcds form page is visited. 
- Right now the way that it's built, it will PATCH this value each time the user visits the rwcds-form page whether the field is already filled or not. I built it out this way based on the assumption that a planner might go into CRM and update fields on the project actions entity after an action is already created. 
Addresses #560

560: manually update dcp_includezoningtextamendment in syncActions function

---

server/src/document/document.controller.ts

This is a temporary fix to allow downloads again. The drawback is that these download links are shareable.
We should revisit this authorization issue when we redo our auth workflow.
The reason this broke was due to my change to authentication: we no longer use cookies to sign API requests. We use authorization headers. However, the download link for documents is a plain HTML link. You can't inject headers in requests for downloads in plain HTML hyperlinks. This meant the request wasn't authenticated.

Enforce auth in documents for everything except GET

---

server/src/http-exception.filter.spec.ts
server/src/http-exception.filter.ts

Rework the HTTP Exception Filter to mold Exceptions to JSON API
compliant error objects before returning them to the client.
Also, response objects from HttpExceptions may be recursively
nested to reflect a stack trace (each level is a layer in the stack).
This flattens them out so that each response
is a top-level item in the errors array.

526 Flatten nested response objects and mold to JSON API format 

---

server/src/http-exception.filter.ts

This patches the exception filter to correctly
reference the *error* response body when unfolding.
Previously it was referencing the HTTP response
body.

526 unfold correct response in exception filter

---

server/src/crm/crm.service.ts
server/src/packages/packages.controller.ts
server/src/packages/packages.service.ts
server/src/projects/projects.controller.ts
server/src/projects/projects.service.ts

This PR standardizes error handling (the format for how errors are thrown) for just the projects and packages controllers and services, and some CRM service methods. As a whole the error handling redesign is getting bigger and more tedious than I first thought, so wanted to first get another round of reactions just these three areas of code.
This standardization trying to implement the guide in #554

526 Standardize Projects &Packages error handling

---

client/app/components/errors/list.hbs
client/app/components/packages/pas-form/pas-form-error.hbs
client/app/components/packages/rwcds-form/rwcds-form-error.hbs
client/app/templates/login-error.hbs
client/app/templates/projects-error.hbs
client/tests/acceptance/error-message-appears-when-save-fails-test.js
client/tests/acceptance/user-can-login-test.js
client/tests/integration/components/errors/list-test.js

This PR unifies the frontend *-error templates
in how they render JSONAPI errors from the backend.
It creates a component, which the templates share,
that iterates through the incoming `errors` array
and renders the keys in each error object.
complements #562

526 Display JSONAPI errors in frontend

---

client/app/templates/pas-form-error.hbs
client/app/templates/pas-form/edit-error.hbs
client/app/templates/pas-form/show-error.hbs
client/app/templates/project-error.hbs
client/app/templates/rwcds-form-error.hbs
client/app/templates/rwcds-form/edit-error.hbs
client/app/templates/rwcds-form/show-error.hbs

This is similar to the work for #596 , but stands up error pages for the remaining templates

526 Add error pages for form edit/show and project routes

---

client/app/components/my-projects/list-item.hbs
client/app/components/ui/external-link.hbs
client/app/controllers/project.js
client/app/models/project.js
client/app/templates/project.hbs

Fix zap-search hyperlink on the projects and project page by:
- making sure the `href` for the `ExternalLink` component is dynamic
- moving the `publicStatusGeneralPublicProject` computed property to the project model and using it in both the list-item component and the singular project page
addresses #585

585: fix zap-search hyperlink on projects page

---

server/src/packages/package-access.guard.ts
server/src/packages/packages.controller.ts

Only allow access to a package if current authenticated
user is on the package's project applicant team
Note that although PackageAccessGuard replaced AuthenticationGuard,
PackageAccessGuard contains the AuthenticationGuard's same basic check for a contactId.
The guard checks for if there is a project where the authenticated contact is within the project's applicant team, and the requested package is among the project's packages. If so, the guard passes.
Addresses #507

507 Add access guard for packages

---

server/src/packages/rwcds-form/rwcds-form.service.ts

For cases where the specific dcp_projectaction row has already been POSTed to dcp_affectedzoningresolution entity...if a planner updates dcp_projectaction entity in CRM afterwards, then syncActions function will check for these changes and PATCH the changes to dcp_affectedzoningresolution. 
addresses #565

565: update syncActions to PATCH updates to dcp_affectedzoningresolution

---

client/app/components/packages/rwcds-form/edit.hbs
client/app/components/packages/rwcds-form/show.hbs

&plus; housekeeping to match rwcds-form show page format to that of edit page (and also figma wireframes)

576 Display package statuscode on rwcds form pages

---

client/app/components/project/package-list-item.hbs
client/app/templates/project.hbs

This PR fixes [AB#12123](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12123) by improving the package lists on the project view: 
- Conditionally show headers 
- Put all items in one list (they were previously each in their own `<ol>`, resulting in a one-item list for each item)

🐞 Package Lists Improvements

---

client/app/validations/saveable-pas-form.js

Patch fix for validating dcpInclusionaryhousingdesignatedareaname
Prevents saving if this field exceeds 50

Add validation for dcpInclusionaryhousingdesignatedareaname, max 50

---

client/app/components/my-projects/list-item.hbs
client/app/components/packages/applicant-fieldset.hbs
client/app/components/packages/pas-form/show.hbs
client/app/components/packages/rwcds-form/edit.hbs
client/app/components/packages/rwcds-form/show.hbs
client/app/components/project/package-list-item.hbs
client/app/controllers/projects.js
client/app/helpers/helpers.md
client/app/helpers/optionset.js
client/app/models/package.js
client/app/models/project.js
client/app/optionsets/applicant.js
client/app/optionsets/package.js
client/app/optionsets/project.js
client/app/templates/project.hbs
client/mirage/factories/package.js
client/tests/integration/helpers/optionset-test.js

This PR makes sure that all optionset keys strictly match their corresponding model field names.
For example, for the Package optionset, use the key `statuscode` instead of `status`, since `statuscode` is an actual field on the Package model. 
`{{optionset 'package' 'statuscode' ....}}`, instead of  `{{optionset 'package' 'status' ....}}`. 
This is important for develop experience, and easy, predictable API for the optionset helper.
This PR also better scopes the exports from optionset files, since multiple optionsets/models may have the same fields (statuscode, statecode, etc.)

Housekeeping: Standardize optionset keys

---

server/src/packages/pas-form/pas-form.service.ts
server/src/packages/rwcds-form/rwcds-form.service.ts

If there is no PAS form on a project, then while loading the RWCDS form, don't copy PAS "project description"  field values into the RWCDS. Just display the usually blank RWCDS form values for those fields.
Addresses #580

12127 Display original RWCDS description fields if no PAS

---

client/app/components/auth/user-badge.hbs
client/app/components/auth/user-badge.js
client/app/controllers/application.js
client/app/templates/application.hbs
client/tests/integration/components/auth/user-badge-test.js

According to NYC.ID terms of use, we must link out to the user's profile on the NYC.ID website. This allows the user to edige their profile: https://www1.nyc.gov/assets/nyc4d/html/services-nycid/account-profile.shtml.
This change takes some of the existing markup for displaying the user email and "log out" link, extracts it into its own component, and hyperlinks that email out to the required NYC.Id profile edit page.
The complexity in here is due to the requirement of NYC.ID to encode the redirect (which occurs afte ruser "saves" their changes to their profile page) uri back to the app. That must be encoded as base64.

Extract user badge to new component; add edit link

---

client/app/controllers/application.js
client/app/controllers/projects.js
client/tests/acceptance/user-sees-projects-of-all-types-test.js
server/src/auth.middleware.spec.ts
server/src/auth.middleware.ts
server/src/auth/auth.service.ts
server/src/packages/package-access.guard.ts
server/src/projects/projects.controller.ts
server/src/projects/projects.service.ts

Fixes [AB#12149](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12149)
- Re-enables creeper mode for all routes, regardless of method.
The changes here move the email-param-bypass behavior into the auth middleware. This middleware then looks up the passed query param (email), generates a new token, and fully simulates the authentication for the "creeped" contact.
Instead of sending the query param explicitly, the API infers the QP from the "referer" header. This seems good enough for an internal-facing debugging feature. Additionally, it removes "creeper mode" behavior from multiple parts of the application
- Removes the IMPOSTER_ID stuff which wasn't being used (and shouldn't be used).
- Removes authorization logic from the project service — …

12149 creeper mode fix

---

client/app/components/project/project-editor-list-item.hbs
client/app/models/contact.js
client/app/models/project.js
client/app/routes/project.js
client/app/templates/project.hbs
client/mirage/config.js
client/mirage/models/contact.js
client/mirage/models/project.js
client/tests/integration/components/project/project-editor-list-item-test.js
server/src/contact/contacts.attrs.ts
server/src/projects/project-applicants/project-applicants.attrs.ts
server/src/projects/projects.controller.ts
server/src/projects/projects.service.ts

This PR employs a double `$expand` (two network requests) in order to get access to contacts that are associated with `dcp_projectapplicants` on the project entity. 
The purpose of this was to replace `dcp_projectapplicants` with `contacts` as list items on the project editor list on the project page.

12019: replace projectApplicants with contacts in project editor list

---

server/src/auth/auth.service.ts
server/src/contact/contact.service.ts
server/src/contact/contacts.attrs.ts

Addresses [AB#12018](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12018) by beginning process of associating NYC.ID's guid with the contact record.
Future improvements may synchronize the contact record based on how long ago it was changed.
This is intended to synchronize with existing users

Synchronize the NYC.ID GUID with the Contact record

---

client/app/models/package.js

This also fixes [AB#12168](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12168) by ensuring
that file manager is synced to latest
package data from CRM/Sharepoint after
a save.

12168 reload package on save

---

client/app/components/packages/pas-form/edit.hbs
client/app/components/packages/rwcds-form/edit.hbs
client/app/components/project/project-editor-list-item.hbs
client/app/components/ui/confirmation-modal.hbs
client/app/controllers/project.js
client/app/helpers/optionset.js
client/app/models/contact.js
client/app/models/project-applicant.js
client/app/models/project.js
client/app/optionsets/contact.js
client/app/optionsets/project-applicant.js
client/app/routes/project.js
client/app/templates/project.hbs
client/tests/integration/components/project/project-editor-list-item-test.js
client/tests/integration/components/ui/confirmation-modal-test.js
server/src/contact/contact.controller.ts
server/src/contact/contacts.attrs.ts
server/src/json-api-deserialize.pipe.ts
server/src/projects/project-applicants/project-applicant.controller.ts
server/src/projects/project-applicants/project-applicants.attrs.ts
server/src/projects/projects.controller.ts
server/src/projects/projects.module.ts
server/src/projects/projects.service.ts

Allow user to create new "project editors" on the project page. 
**Overall Behavior**
- When a user enters first name, last name, and email address into the project editor form, they are prompted with a confirmation modal and allowed to save this new project editor. 
- If a contact that matches that email address is already created, then the only POST that occurs is on the project applicant entity associated with the current project. 
- If a contact does NOT exist that matches the email address entered, then a POST will occur on both the contact entity and the project applicant entity
**Server Behavior**
- While we are only creating a record and saving it for project applicants on the frontend, we also POST a new contact in the server when we POST on the `project-applicant.controller` …

12019: user can create new contact record associated with project on project editors list

---

client/app/controllers/project.js
client/app/models/project-applicant.js
server/src/projects/project-applicants/project-applicant.controller.ts

dcp_name field in projectApplicant entity is automatically filled with the firstname and lastname fields in the contact entity. In order to get accurate firstname and lastname values (instead of having to use regex), we have "fake" firstname and lastname attributes in the frontend project-applicant model so we can send to backend.

12019: add firstname and lastname attributes for ease of POSTing to project applicant

---

client/app/models/applicant.js
client/app/models/bbl.js
client/app/models/landuse-action.js
client/app/models/landuse-form.js
client/app/models/related-action.js
client/mirage/models/applicant.js
client/mirage/models/bbl.js
client/mirage/models/landuse-form.js
client/mirage/models/package.js
client/tests/unit/models/landuse-action-test.js
client/tests/unit/models/landuse-form-test.js
client/tests/unit/models/related-action-test.js

Create basic model structure for land use form. 
**New models**: `landuse-form`, `landuse-action`, `related-action`
**`landuse-form` model has these relationships:** 
- **hasMany**: `bbl`, `applicant`, `landuse-action`, `related-action`
- **belongsTo**: `package`
Closes [AB#12239](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12239)

12239: create model for land use form and associated relationships

---

client/app/components/auth/sign-in.hbs
client/app/styles/app.scss
client/app/templates/index.hbs

- add id to email input so label targets it
- update sign in help text w/ contact info
- nix href on button
- adjust grid so next button follows email input on small screens
- limit width of sign in grid on medium screens

12018 new auth  ac

---

client/app/components/packages/rwcds-form/show.hbs

This PR adds template logic to conditionally show the Proposed Actions sub questions if they were answered, and to show a "No additional info" message if the Action has no data. 
Fixes [AB#12161](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12161)

🥾🐜 Conditionally show Proposed Actions sub question

---

client/app/components/packages/landuse-form/edit.hbs

The Land Use SaveableForm model argument should be the form itself.
We have differing saveable form setups for PAS and RWCDs "edit" components: 
The PAS component wraps the form-based saveableForm in a package-based saveableForm.
The RWCDs component simply renders a form-based saveableForm 
And so far for Land Use we're following the pattern of the RWCDs form.

Pass the form as @model argument to land use SaveableForm component

---

client/app/components/packages/rwcds-form/project-description.hbs
client/app/routes/landuse-form.js
server/src/packages/landuse-form/landuse-form.service.ts
server/src/packages/packages.controller.ts

Backed code to support loading applicants of a landuse form, on package load. 
Partly fixes [AB#12252](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12252)

12252 Backends loads Applicants along with Land Use form

---

client/tests/acceptance/user-can-login-test.js
client/tests/integration/components/auth/sign-in-test.js
server/src/auth/auth.service.ts
server/src/authenticate.guard.ts
server/src/contact/nycid/nycid.service.ts

Fixes minor bug which allowed non-email types to return a "is-registered" 
Bumps test coverage

Return "is-registered" flag for non-email accounts

---

server/src/contact/contact.service.ts
server/src/contact/nycid/nycid.service.ts
server/yarn.lock

This is why this service is a top candidate for a REDO. We need to flag that it has a CRM contact unless the “default” non-crm record is used.

Make sure to default “has crm contact”

---

client/app/components/packages/landuse-form/edit.hbs
client/app/components/packages/landuse-form/site-information.hbs
client/tests/acceptance/user-can-click-landuse-form-edit-test.js

This PR sets up the Site Information section on the Land Use form, including basic acceptance tests.
Creates a basic component that placed in the `landuse-form/edit.hbs` component
The acceptance tests currently assert against the Mirage database. Later, when we set up the Land Use Show page,
we should refactor the tests to assert that the submitted Site Info shows up on the Show page.
Fixes [AB#12251](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12251)

12251 Set up Land Use Site Information section

---

client/app/components/packages/landuse-form/edit.hbs
client/app/components/packages/landuse-form/primary-contact.hbs
client/tests/acceptance/user-can-click-landuse-form-edit-test.js

User can enter primary contact information on the landuse-form
landuse-form
- created a new component `packages/landuse-form/primary-contact` that is rendered on the landuse-form. These fields are part of the `dcp_landuse` entity and so are on the `landuse-form` model. 
- test for primary contact form added to landuse-form acceptance test
Closes [AB#12250](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12250)

12250: create component for primary contacts on landuse-form

---

client/app/components/packages/landuse-form/attached-documents.hbs
client/app/components/packages/landuse-form/edit.hbs

User can upload/delete files on the landuse form
The Land Use Form
Recycle the `packages/attachments` and `packages/landuse-form/attached-documents` components, render on the landuse form. 
Closes [AB#12260](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12260)

12260: add attachments component to landuse form

---

client/app/components/packages/landuse-form/edit.hbs
client/app/components/packages/landuse-form/edit.js
client/app/components/packages/landuse-form/project-information.hbs
client/app/models/landuse-form.js
client/app/models/package.js
client/app/validations/saveable-project-form.js
client/app/validations/submittable-project-form.js
client/mirage/config.js
client/tests/acceptance/user-can-click-landuse-form-edit-test.js
server/src/projects/projects.controller.ts

User can edit the associated project name on the landuse form.
Land Use Form
A new component was created `packages/landuse-form/project-information` which is rendered on the landuse form. This component handles renaming a project and PATCHes to the `dcp_project` entity (the `project` model). 
Closes [AB#12249](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12249)

12249: user can edit project name on landuse form

---

client/app/components/packages/landuse-form/edit.hbs
client/app/components/packages/landuse-form/environmental-review.hbs
client/app/helpers/optionset.js
client/app/optionsets/landuse-form.js
client/tests/acceptance/user-can-click-landuse-form-edit-test.js

User can edit Environmental Review information on the landuse form.
The landuse form
This PR adds a new component that allows users to enter information on the landuse form for the Environmental Review section. The fields in this section are on the `dcp_landuse` entity (the `landuse-form` model)
Closes [AB#12257](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12257)
**NOTE**: This implementation differs from the wireframes, two input boxes were left out
- `dcp_leadagency` was originally assumed to be a direct string field on the `dcp_landuse` entity, but it requires an `expand` and includes an entire object of data. In CRM the input …

12257: create environmental review component on landuse-form

---

client/app/components/packages/landuse-form/edit.hbs
client/app/components/packages/landuse-form/edit.js
client/app/components/packages/landuse-form/project-area.hbs
client/app/components/packages/landuse-form/project-area.js
client/app/helpers/optionset.js
client/tests/acceptance/user-can-click-landuse-form-edit-test.js

This PR sets up the Project Area section in the Land Use Form
Fixes [AB#12254](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12254)
Land Use Form -- Project Area
Due to the series of cascading questions and the current pattern/design of our form and fields, this component does get rather gnarly. In order to reference the value of a previous radio group question, currently our form pattern calls for the previous radio value to be yielded within the block-form rendering of a radio-group component. The subsequent radio group must sit within the previous group's block so that it can be conditionally displayed based on the yielded value. Since there is a chain of radio groups, each depending on the value of the previous group, there is heavy …

12254 Set up Land Use Project Area section

---

client/app/authenticators/zap-api-authenticator.js
client/package.json
client/yarn.lock

Proposing we add this so that the email is included in server logs when attempting to debug login attempts for a specific user
Error-handling!
Adds a jwt decoder lib. Decodes (but not validates) the jwt client-side, extracts the email associated, and sends with the login request. This appears in Papertrail alerts and logs for better debugging experience.

Display email in login attempt

---

.github/workflows/auto-pr.yml

- adding auto pr github actions (from develop to landuse-form)
- if PR already created, no new PR will be created
- cron job scheduled at 0:00 everyday
- repository dispatch for manual trigger
modeled after https://github.com/marketplace/actions/github-pull-request-action

adding github actions auto PR workflow

---

client/app/components/packages/landuse-form/edit.hbs
client/app/components/packages/landuse-form/proposed-development-site.hbs
client/app/helpers/optionset.js
client/app/optionsets/landuse-form.js
client/app/validations/submittable-landuse-form.js
client/tests/acceptance/user-can-click-landuse-form-edit-test.js

This sets up the Proposed Development Site section for the Land Use form
Land use - proposed development site
Fixes [AB#12255](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12255)
The component design is similar to that for Project Area. 
We use component nesting to implement conditional/cascading questions.

12255 proposed development site

---

client/app/components/packages/landuse-form/edit.hbs
client/app/components/packages/landuse-form/edit.js
client/app/components/packages/landuse-form/project-tax-lots.hbs
client/app/components/packages/pas-form/edit.hbs
client/app/components/packages/pas-form/edit.js
client/app/components/packages/pas-form/project-geography.hbs
client/app/components/packages/project-geography.hbs
client/app/components/packages/project-geography.js
client/app/models/package.js
client/app/validations/submittable-landuse-form.js
client/tests/acceptance/user-can-click-landuse-form-edit-test.js

Previously, users had to click save twice in order to properly DELETE `relatedActions` and `applicants`. 
PAS form and Land Use Form -- the applicants and related actions sections
A while back, we switched from `destroyRecord` to `deleteRecord`. Since then, when we looped through the records with dirty attributes and only saved those records, we were not taking into account records that had been deleted -- these records did not show up in the array and were therefore not saved. This PR passes the records that are currently being "removed" to the package model to be saved. 
Closes [AB#12354](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/e …

12354: fix bug where deleted records were not being saved

---

client/app/models/project.js
client/app/models/team-member.js
client/app/routes/project.js
client/app/templates/project.hbs
client/mirage/models/project.js
client/mirage/models/team-member.js
client/tests/unit/models/team-member-test.js
server/src/projects/projects.controller.ts
server/src/projects/projects.service.ts
server/src/projects/team-members/team-members.attrs.ts

This PR shows the DCP Team in the project page contact management section
Contact Management
It wasn't displaying the DCP team members and this PR displays them in their full glory according to the REQS
It makes another request to the CRM API to add the information about DCP team members alongside the project applicants (think of these entities as siblings). It then does some idiosyncratic munging of that data (sorry, but some of the data is on a separate related entity).
This PR is "pretty bad" in terms of our code standards. There isn't any additional test coverage for this part of contact mgmt (although AFAICT there wasn't any for that feature to begin with), and this makes several assumptions about the data that's being pulled (it's not clear if we're using the correct phone number …

Add team member model; extract data from CRM; expands on proejct service

---

client/app/components/packages/landuse-form/edit.hbs
client/app/components/packages/landuse-form/edit.js
client/app/components/packages/landuse-form/landuse-form-error.hbs
client/app/components/packages/landuse-form/show.hbs
client/app/components/packages/rwcds-form/edit.hbs
client/app/templates/landuse-form/show.hbs
client/tests/acceptance/user-can-click-landuse-form-edit-test.js

Set up a blank Land use form "Show" page and route, along with associated error templates.
Also sets up the Land Use form Submit button and confirmation modal. Most language in the confirmation modal copied
from RWCDS form. Clicking Confirm on the modal triggers transition to the Show page.
Land use form submission 
Fixes [AB#12366](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12366)
- The new `packages/landuse-form/landuse-form-error.hbs` component template is to support the confirmation modal footer.
- Also fixes the a typo with the `@ continueButtonTitle` argument on rwcds form confirmation modal
- Fixes typo (`land-use.show`) in route name passed to submit button transitionTo

12366 Set up Land Use "show" page, wire up Submit button

---

server/src/auth.middleware.ts

Before, it was using the real user’s GUID, which is what the auth#generateNewToken method prefers. Now, this sets that as null

Creeper mode: Force token spoofing to include a null NYC.ID GUID

---

client/app/templates/auth/register.hbs
server/src/auth/auth.service.ts

This change syncs the NYC.ID firstname/lastname information with CRM only if the GUIDs match.
This is to prevent any “mixing” issues that might happen with creeper mode.
A later refactor should find a safer way to deal with information synchronization, among other auth issues...
Closes [AB#12365](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12365)

Prefer NYC.ID firstname,lastname for contact records

---

client/app/templates/auth/register.hbs
server/src/auth/auth.service.ts

Closes [AB#12398](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12398)
When the user creates an applicant Portal account and then confirms his/her email the corresponding system generated contact record's "Is Enabled Portal user?" field should be 'yes'
currently it is displaying as 'no'

12398 enable for portal

---

client/app/components/project/project-editor-list-item.hbs

Not when they’re already registered
Addresses [AB#12455](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12455)
Change it back to `unless` bc lint prefers that? IDC as long as it's not a double negative!

Show invitation button when user isn’t registered

---

client/app/components/packages/landuse-form/edit.hbs
client/app/components/packages/landuse-form/project-tax-lots.hbs
client/app/components/packages/landuse-form/proposed-development-site.hbs
client/tests/acceptance/user-can-click-landuse-form-edit-test.js

Part of the Land use form is shown only when the Project applies to a partial area, and not to entire the city/borough/community or lot (i.e. the four respective LU fields relating to project area all evaluate to "false")
Fixes [AB#12413](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12413)
Form inputs are updating the changeset held at `saveableForm.data`, which is made available through the `saveableForm` yield in the `landuse-form/edit` component. Thus to access the responses to the city/borough/community/lot radio questions held in `saveableForm.data`, the conditional business logic for this PR is implemented in `landuse-form/edit.hbs` through template truth helpers (In contrast to through a controller or model file)
**- A subsequent PR …

12413 Conditionally show LU dev site and tax lots sections

---

client/app/components/packages/landuse-form/edit.hbs
client/app/components/packages/landuse-form/project-area.hbs
client/app/components/packages/landuse-form/project-tax-lots.hbs
client/app/components/packages/landuse-form/proposed-development-site.hbs
client/app/helpers/optionset.js
client/tests/acceptance/user-can-click-landuse-form-edit-test.js

There are four fields at the end of the Project Area section which haven't been added. They also only show up the answers to previous four questions (about applicability to city/borough/community/lot)  are all "No".
[AB#12412](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12412) 
- Builds off the commits from the PR for [AB#12413](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12413)
- Tests added

12412 add missing project area fields

---

client/app/components/packages/landuse-form/edit.hbs
client/app/components/packages/landuse-form/housing-plans.hbs
client/app/helpers/optionset.js
client/app/models/landuse-form.js
client/app/optionsets/common.js
client/app/optionsets/landuse-form.js
client/tests/acceptance/user-can-click-landuse-form-edit-test.js

Sets up the first part of the LU Housing Plans section. This first part only PATCHes to dcp_landuse, and not another entity (like dcp_sitedatahform)
Land Use -- House Plans
Fixes [AB#12355](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12355)
- Very similar to previous components with cascading forms.
- For these housing plan optionsets, I extended them from COMMON_OPTIONSETS.YES_NO optionsets.
These housing plan optionsets are essentially YES_NO optionsets; they share the same code values but have a slightly customized labels.

12355 Set up LU Housing Plans section

---

client/app/controllers/project.js
client/app/templates/project.hbs

This PR… 
- Cleans up the Contact MGMT UI
- Adds a `contactMgmtOpen` var, a `toggleContactMgmt()` function, and a button to enable/disable editing Project Editors
- Make the sidebar scroll with page (not sticky like form menus)
- Removes crufty grid and Q markup from "Add Project Editors" form

💄 Contact MGMT UI

---

client/app/components/auth/do-logout.js

The component originally only called the nyc.id logout service through an iFrame. This now also invalidates the client’s ember-simple-auth session.

DoLogout component also invalidates simple-auth session

---

client/app/components/packages/landuse-form/edit.hbs
client/tests/acceptance/user-can-click-landuse-form-edit-test.js

Only display the Housing Plans and Subject Sites (to be set up in future PR) sections if the Project Land Use Actions includes a certain set of action codes.
Land Use - Housing Plans and Subject Sites 
[AB#12355](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12355) 
We write the logic in `landuse-form/edit.hbs` because multiple sections/components (Housing Plans and Subject Sites) will be toggled based on the condition.

12355 Conditionally display housing-related Land Use sections

---

client/app/authenticators/zap-api-authenticator.js
client/app/components/auth/user-badge.js
client/app/router.js
client/app/routes/auth/sync.js
client/tests/acceptance/user-can-login-test.js
client/tests/unit/routes/auth/sync-test.js
server/src/app.controller.ts
server/src/auth/auth.service.ts
server/src/contact/contact.controller.ts
server/src/contact/contact.service.ts
server/src/contact/nycid/nycid.service.ts
server/src/crm/crm.service.ts

Addresses [AB#12365](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12365) 
This PR makes sure that the first and last names of CRM contacts are synced to the respective values in NYCID, after a user has edited their profile on NYCID. 
Includes a new client auth route, "sync", which is the redirect location after a user updates the profile on NYCID. 
The route infers that the user has updated their profile if the browser "referrer" is the NYC.ID user profile edit page. If so, it triggers new backend methods to request the updated user first and last name from NYCID, and then send the info to CRM.
The sync route does so by triggering the save() method on the contact model. The save() method hits a new backend Contact PATCH endpoint, which …

Use NYC.ID oauth user endpoint; create synchronize method

---

client/app/components/project/project-editor-list-item.hbs
client/app/controllers/project.js
client/app/templates/project.hbs
client/config/environment.js

This PR… 
- Adds a config var to enable the Contact MGMT features (`true` be default, `false` in production environment) 
- Improves the UI of the Contact MGMT section by 
- Associating the "Manage/Cancel" button w/ the section header (it seemed like part of the "Add Editor" form)
- Replaces the user icon with an X if `@canDelete` (so it's more direct association w/ user instead of aligned to the far right)
- Adds tooltips that show when you enable editing to highlight what's editable
- Condenses the "Add Editor" form 
- Uses the `<Ui::GenericModal>` instead of the confirmation modal
- Improves the spacing and dividing rules of sections of the page (e.g. horizontal line between packages, appropriate spacing between sidebar sections)

Contact MGMT improvements

---

client/app/components/packages/landuse-form/edit.hbs
client/app/components/packages/landuse-form/public-facilities.hbs
client/app/components/packages/landuse-form/public-facilities.js
client/app/components/saveable-form/field/radio.hbs
client/app/components/saveable-form/field/radio.js
client/app/helpers/optionset.js
client/app/models/landuse-form.js
client/app/optionsets/common.js
client/app/optionsets/landuse-form.js
client/app/routes/landuse-form.js
client/app/validations/saveable-landuse-form.js
client/tests/acceptance/user-can-click-landuse-form-edit-test.js

Sets up Public Facilities section
Fixes [AB#12391](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12391)
- Introduces the YES_NO_INTEGER optionset to accommodate the unfortunate Yes/No options which map to 1 and 0, instead of true and false. 
- Uses native Ember Input component to render checkboxes tied to integer values, since our Checkbox component assumes boolean values.
- Introduces the `data-test-checked` and `aria-checked` attributes to Radio components so that we can assert their checked state in tests
- Re-use the pattern for clearing dependent fields introduced in the housing-plans section

12391 public facilities

---

client/app/components/packages/landuse-form/proposed-actions.hbs
client/app/components/packages/landuse-form/proposed-actions.js
client/app/helpers/optionset.js
client/app/models/landuse-form.js
client/app/optionsets/landuse-form.js
client/tests/acceptance/user-can-click-landuse-form-edit-test.js

- New section added to landuse-form for "Zoning Special Permit, Authorization, and Certification"
- These questions were just added to the `proposed-action.hbs` file
Closes [AB#12393](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12393)

12393: add zoning permit, authorization, and certification section to landuse-form

---

server/src/auth/auth.service.ts

Prefer updating the contact record when the GUID is a mismatch (including an empty GUID field). This is so that the accounts can update when we switch environments.

Update when GUID mismatch, not falsey

---

server/src/auth/auth.service.ts

This adds an extra condition to ensure an “exact” but case-insensitive e-mail match before overwriting the previously-stored GUID.
Because users will have to re-register, they will have new GUIDs. This change makes sure that the e-mail on the NYC.ID at least also matches before overwriting the GUID (in case something goes wrong or "creeper mode" is enabled).
Auth

Adds an extra condition to ensure email exact match

---

client/app/components/packages/applicant-fieldset.hbs
client/app/components/packages/land-use-action.hbs
client/app/components/packages/landuse-form/proposed-action-editor.hbs
client/app/styles/app.scss
client/ember-cli-build.js
client/package.json
client/yarn.lock

re-attempt an upgrade of labs-ui to avoid failing tests. Nothing was really changed, but after redo tests were passing. 
Closes [AB#12467](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12467)

12467: upgrade labs-ui REDO

---

client/config/environment.js
netlify.toml

When deployed to any environment, Ember's internal setting is always "production."
When I switched the NYC.ID domain to prod, it caused non production environments to break because they were pulling NYC.ID guids from the non-prod environment and using those to query the prod env.
This change provies an env variable to override that domain to non-prod.

Prefers and adds env variable for domains

---

server/src/packages/pas-form/applicants/applicants.controller.ts

**What was wrong and how does this fix the problem?**
User was unable to save applicants on the Other Team Member section of the applicants component on the landuse-form. This was due to a typo in the POST on the `applicants.controller.ts`, where the incorrect entity was listed. This PR fixes the typo so that users can save to the correct entity. 
Closes [AB#12654](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12654)

12654: fix typo in POST for applicant representative

---

client/app/controllers/project.js
client/app/controllers/projects.js
client/app/templates/project.hbs

Defaults to hiding Land Use packages on the Project page, and to
list Projects with active Land Use packages under "other". 
A user can append `?landuse=true` to the `/projects` and `/project/<project_id>` routes to
show LU packages and see Projects with active LU packages under
"Await submission"
Fixes [AB#12414](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12414)

12414 QP to list lu projs under awaiting submission

---

client/app/components/packages/landuse-form/edit.hbs
client/app/components/packages/landuse-form/environmental-review.hbs
client/app/components/packages/landuse-form/lead-agency.hbs
client/app/components/packages/landuse-form/lead-agency.js
client/app/models/account.js
client/app/models/landuse-form.js
client/app/models/lead-agency.js
client/app/routes/landuse-form.js
client/app/templates/landuse-form/edit.hbs
client/mirage/config.js
client/mirage/models/account.js
client/mirage/models/landuse-form.js
client/mirage/models/lead-agency.js
client/tests/acceptance/user-can-click-landuse-form-edit-test.js
server/src/accounts/accounts.attrs.ts
server/src/accounts/accounts.controller.ts
server/src/accounts/accounts.module.ts
server/src/app.module.ts
server/src/packages/landuse-form/landuse-form.attrs.ts
server/src/packages/landuse-form/landuse-form.controller.ts
server/src/packages/landuse-form/landuse-form.service.ts
server/src/packages/packages.controller.ts

Users can use a dropdown to search and select a lead agency (e.g. DOE) on the Environmental Review section of the Land Use Form.
Draft Land Use Form
- A **new componen**t was created called `lead-agency` that is rendered on the `environmental-review` component, which is then rendered on the landuse-form
- We have a GET for the `accounts` entity in order to **display a list of all accounts** that match the desired criteria in a dropdown. 
- When a user selects an option from the **dropdown**, the field `chosenLeadAgencyId`, which is just a made-up field and does not exist in CRM, is updated to match the id of the account selected. 
- When the user saves the landuse-form, this …

12401: lead-agency section on landuse form

---

client/app/components/packages/landuse-form/edit.hbs
client/app/components/packages/landuse-form/edit.js
client/app/components/packages/landuse-form/zoning-text-amendment-fieldset.hbs
client/app/components/packages/landuse-form/zoning-text-amendment.hbs
client/app/components/packages/pas-form/project-information.hbs
client/app/components/saveable-form/field.hbs
client/app/components/saveable-form/field/text-input.hbs
client/app/models/affected-zoning-resolution.js
client/app/models/landuse-form.js
client/app/models/package.js
client/app/routes/landuse-form.js
client/app/validations/saveable-affected-zoning-resolution-form.js
client/mirage/config.js
client/mirage/models/affected-zoning-resolution.js
client/mirage/models/landuse-form.js
client/tests/acceptance/user-can-click-landuse-form-edit-test.js
server/src/json-api-deserialize.pipe.ts
server/src/packages/landuse-form/landuse-form.service.ts
server/src/packages/packages.controller.ts
server/src/packages/rwcds-form/affected-zoning-resolution/affected-zoning-resolutions.controller.ts

Add Zoning Text Amendment section to the Land Use Form. This section allows users to "add" a ZR Section which then displays a form (per each ZR Section added) that has two input questions. Users can also remove these "ZR Sections"
Land Use Form
- Two components were created to handle this functionality. One was the `zoning-text-amendment-fieldset` which handles the two input questions and the "Delete ZR Section" button. This `fieldset` component was then rendered on `zoning-text-amendment.hbs` which handles the title and "adding" functionality. This component is then rendered on the landuse form. 
- This component saves fields on the `affected-zoning-resolution` model, so a …

12394: add zoning text amendment section on landuse-form

---

client/app/components/packages/landuse-form/attached-documents.hbs
client/tests/acceptance/user-can-click-landuse-form-edit-test.js

Add instruction text, to the Draft Land Use attachments section.
Some of it is conditional upon a certain actions.
Fixes [AB#12399](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12399)
Fixes [AB#12679](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12679)

12399 Add Land Use Attachments language

---

client/app/components/packages/landuse-form/edit.hbs
client/app/components/packages/landuse-form/edit.js
client/app/components/packages/landuse-form/zoning-map-amendment-fieldset.hbs
client/app/components/packages/landuse-form/zoning-map-amendment.hbs
client/app/helpers/optionset.js
client/app/models/landuse-form.js
client/app/models/package.js
client/app/models/zoning-map-change.js
client/app/optionsets/landuse-form.js
client/app/optionsets/zoning-map-change.js
client/app/templates/landuse-form/edit.hbs
client/app/validations/saveable-zoning-map-change.js
client/app/validations/submittable-zoning-map-change.js
client/mirage/config.js
client/tests/acceptance/user-can-click-landuse-form-edit-test.js
server/src/json-api-deserialize.pipe.ts
server/src/packages/landuse-form/landuse-form.service.ts
server/src/packages/landuse-form/zoning-map-changes/zoning-map-change.attrs.ts
server/src/packages/landuse-form/zoning-map-changes/zoning-map-change.controller.ts
server/src/packages/packages.controller.ts
server/src/packages/packages.module.ts

Sets up the Draft Land Use Zoning Map Amendment Section
Fixes [AB#12395](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12395) 
Mostly follow the same patterns as other sections. Some nice-to-knows:
- This PR sets an example for calling *-fieldset components going forward. Notice how the zoning-map-amendment-fieldset component is called without the @zoningMapChange argument, since that argument is redundant and confusing.
- Similarly this PR sets an example for calling the `@ remove<fieldset>` actions. Previously in other sections we passed an extra, unnecessary argument to the `@ remove<fieldset>` action inside the *-fieldset file (at the remove button). 
- We should later assess whether the …

12395 draft lu zoning map amendment

---

server/src/json-api-deserialize.pipe.ts
server/src/json-api-serialize.interceptor.ts

Fixes [AB#12572](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12572) (answeres to the dcp_500kpluszone question was not getting written to/read from CRM)
It turns out our current Nest de/serialization and CRM is at odds with
Ember Data in regards to whether digits appear
before for after a dash/underscore. Thus we have to implement
custom serialization/deserialization for attributes with
digit tokens.
When generating JSONAPI request payloads, Ember Data dasherizes model properties by
1. placing dashes before any capital letters. Note this is only letters but not numbers
2. lowercasing the capital letters
When generating models from JSONAPI response payloads, Ember Data does the reverse:
1. capitalizing letters that immediately follow a dash …

12672 Patch de/serialization for dcp_500kpluszone

---

client/app/components/packages/related-action-fieldset.hbs
client/app/helpers/optionset.js
client/tests/acceptance/user-can-click-landuse-form-edit-test.js

Fixes [AB#12713](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12713), and the duplicate [AB#12475](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12475)
Conveniently Fixes [AB#12714](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12714) as well (the wrong attribute was used for that question).
Also makes critical patches to adjacent code in `related-actions-fieldset.hbs`:
- Standardize dcpIscompletedaction radio group to use "radio-group" input type and optionset helper
- Add showCounter and maxlength attributes to fields to activate validation UI
- Uses the Ui::Question component instead of plain labels

12713 12714 Fix Related Actions labels, validation, attribute

---

client/app/components/project/package-list-item.hbs
client/app/models/package.js
client/app/models/project.js
server/src/packages/packages.service.ts

Originally meant to roughly spike an end-to-end setup of Filed Land Use form, but this can probably already satisfy the basic user stories.
This proves that Filed Land Use not only can re-use the same components, but can even re-use the same models, routes and
backend API controllers and services, since a Filed Land Use Package+Form is essentially a Draft Land Use Package+Form but with a different Package "type" value. 
Fixes #774 
- Both Filed and Draft Land Use forms make use of the `dcp_landuse` entity to represent the form, so we did not need to set up a new *-form controller or service for a new form type. 
- The only thing distinguishing a Draft from a Filed Land Use form is the associated Package's type (filed or draft)
- Upon Draft Land Use Form submission and sign-off by DCP, CRM …

12887 Basic set up for Filed Land Use

---

client/app/controllers/project.js
client/app/controllers/projects.js
client/app/templates/project.hbs

Enables by default the Land Use section on the Project page, and makes sure that that projects with active Draft or Filed Land Use packages appear under Awaiting Submission. 
Removes the use of `landuse=` queryParam to toggle those sections.
Fixes [AB#12722](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12722) [AB#12775](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12775)

12722 12775 Enable Land Use section of Project(s) pages

---

client/app/components/packages/landuse-form/housing-plans.hbs
client/app/components/packages/landuse-form/housing-plans.js
client/app/models/landuse-form.js
client/app/validations/saveable-landuse-form.js
client/app/validations/submittable-landuse-form.js
client/tests/acceptance/user-can-click-landuse-form-edit-test.js

Adds fields for dcpFrom and dcpTo to the Housing Plans section.
They are conditionally shown when dcpMannerofdisposition is "Direct"
Fixes [AB#12777](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12777)

12777 Add conditional fields to Housing Plans

---

client/app/components/project/package-list-item.hbs

Adds icons next to packages to indicate their visibility. 
Also reformats the package list item to better match the wireframes 
Fixes [AB#12721](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12721)

12721  Add visibility icons next to packages

---

client/app/components/project/package-list-item.hbs

This makes sure that the Package list UI matches the wireframes:
- There's a new "edit" orange button for the latest version of a package
- only the button has an edit icon
Fixes [AB#12728](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12728)

12728 edit package button

---

client/app/components/packages/landuse-form/edit.hbs
client/app/components/packages/landuse-form/proposed-action-editor.hbs
client/app/components/packages/landuse-form/proposed-actions.hbs
client/app/components/packages/landuse-form/zoning-resolution-dropdown.hbs
client/app/components/packages/landuse-form/zoning-resolution-dropdown.js
client/app/models/landuse-action.js
client/app/models/zoning-resolution.js
client/app/routes/landuse-form.js
client/app/templates/landuse-form/edit.hbs
client/mirage/config.js
client/mirage/models/landuse-action.js
client/mirage/models/zoning-resolution.js
client/tests/acceptance/user-can-click-landuse-form-edit-test.js
server/src/app.module.ts
server/src/json-api-deserialize.pipe.ts
server/src/packages/landuse-form/landuse-actions/landuse-actions.controller.ts
server/src/packages/landuse-form/landuse-form.service.ts
server/src/packages/packages.controller.ts
server/src/zoning-resolutions/zoning-resolutions.attrs.ts
server/src/zoning-resolutions/zoning-resolutions.controller.ts
server/src/zoning-resolutions/zoning-resolutions.module.ts

Create a new Zoning Resolution dropdown that is part of the Proposed Actions section on the Land Use Form.
Proposed Actions section of the Land Use Form
- all zoning resolution names and ID's in CRM (around 600 records) are loaded onto the landuse-form. These zoning resolution names are used for the options list in the dropdown.
- when a user selects an option from the dropdown a Zoning Resolution id is sent to the backend and when the `dcp_landuseaction` entity is PATCHed, the zoning resolution id is binded to the landuseAction using the `dcp_zoningresolutionsectionactionispursuantto` field
**NOTE**: for the sake of time I created a fake ID field on the landuse-action model …

12683: add zoning resolution dropdown to proposed actions component on landuse-form

---

client/app/components/auth/sign-in.hbs
client/app/components/auth/sign-in.js
client/tests/integration/components/auth/sign-in-test.js

Disable the sign-in Next button while it queries contacts. This dramatically improves the sign-in UX. 
Fixes [AB#12549](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12549)

12549 Disable Sign-In Next btn and email input after click

---

client/app/components/packages/draft-eas/attached-documents.hbs
client/app/components/packages/draft-eas/edit.hbs
client/app/components/packages/draft-eas/edit.js
client/app/components/packages/filed-eas/edit.hbs

Set up SaveableForm, Attachments section, and save button for the Draft EAS package page.
Fixes [AB#13030](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13030)
Fixes [AB#13032](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13032)
Our SaveableForm component worked well! It was able to act on a package model instead of a form model.
And it worked without passing in any validations.

13030 13032 Draft EAS attachments & Save button

---

client/app/components/packages/landuse-form/edit.hbs
client/app/templates/landuse-form/edit.hbs
client/app/templates/landuse-form/show.hbs

Makes sure that "Draft" or "Filed" is displayed at the top of the Land Use Edit component, and also in the bread crumbs.
Fixes [AB#13055](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13055)

13055 Indicate Draft or Filed on Land Use pages

---

client/app/components/packages/landuse-form/show.hbs

Complete task 12406
Add the following items
“Additional data to differentiate multiple actions of same type” field in the All Proposed Actions Section.
"Is the action completed" question under the related action section
Missing sections mentioned above has been added 
Add Answer UI accordingly

complete 12406

---

client/app/components/packages/filed-eas/edit.hbs
server/src/packages/packages.attrs.ts

**Summary**
Display package notes on the Filed Eas package page
**Task/Bug Number**
Closes [AB#13039](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13039)
**Technical Explanation**
Display text from the field `dcpPackagenotes` on the `edit.hbs` file of the filed-eas package.

13039: add package notes to filed eas package

---

client/app/components/project/package-section.hbs
client/app/models/project.js
client/app/templates/project.hbs

Apply the new PackageSection component to EAS, EIS and Technical Memo sections
- Also moves the check for existing packages (`{{#if @packages.length}}`) inside PackageSection, to reduce repeated code. 
- Also minor patch to display Final EIS (FEIS) first before Draft EIS, to be consistent with other Package sections. 
Fixes [AB#13196](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13196)

13196 retrofit PackageSection

---

client/app/index.html
server/src/auth.middleware.ts
server/src/projects/projects.controller.ts

Takes a simpler approach, removes the dangerous “imposter” capability which re-generated the entire token.
Allows the "email" param on the /projects view. Will show assigned projects for that e-mail.
[AB#12660](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12660)
Inserts the `email` search param into the session, allowing it to be referenced as-needed. Right now, the implementation is simplistic because it's only really needed in one place (dcp users may still view projects and forms that are not theirs). If we need to have this in other places, we should consider a pipe or guard or something that'll extract the correct "creeped" contcctid and swap teh current session with that id.

Re-enables the “email” param

---

client/app/components/packages/filed-eas/attached-documents.hbs
client/app/components/packages/filed-eas/edit.hbs
client/app/components/packages/filed-eas/edit.js

**Summary**
Add save button and attachments section to Filed EAS package
**Task Number**
[AB#13038](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13038) (attachments section)
[AB#13040](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13040) (save button)
**Technical Explanation**
Create attachments components for filed-eas package and render it on the filed-eas `edit.hbs` page. Include `saveableForm` and render the save button on the filed-eas `edit.hbs` page.

13038: add save button and attachments section to filed eas package

---

.gitignore
client/app/components/packages/deis/edit.hbs

Display package notes on the DEIS package page
Close AB# [13051
](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/13051)
Display text from the field dcpPackagenotes on the edit.hbs file of the deis package.

13051 Display Package Notes in DEIS

---

client/app/components/packages/draft-eas/attached-documents.hbs
client/app/components/packages/draft-eas/edit.hbs
client/app/components/project/package-section.hbs
client/mirage/factories/package.js
client/tests/acceptance/user-can-edit-draft-eas-test.js

Sets up tests for Draft EAS. Provides basic coverage of the Draft EAS component to boost project coverage.
Fixes [AB#13209](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13209) 
- Introduces test selectors to the Edit component, Package notes section, and Attached documents section.

13209 Set up tests for Draft EAS

---

client/app/components/packages/draft-eas/draft-eas-error.hbs
client/app/components/packages/draft-eas/edit.hbs
client/app/components/packages/draft-eas/edit.js
client/app/components/packages/draft-eas/show.hbs
client/app/templates/draft-eas/show.hbs
client/tests/acceptance/user-can-edit-draft-eas-test.js

Sets up the submission process and Show page for the Draft EAS. Sets up tests as well.
Fixes [AB#13033](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13033)
Fixes [AB#13034](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13034)
- We can't yet acceptance-test that a file upload completes and the uploaded file shows up on the Show page. We have to create a test where the uploaded files are pre-populated on the test package.

13033 13034 Submission and and Show page for Draft EAS

---

client/app/components/packages/technical-memo/attached-documents.hbs
client/app/components/packages/technical-memo/edit.hbs
client/app/controllers/projects.js
client/mirage/factories/package.js
client/tests/acceptance/user-can-edit-technical-memo-test.js

Follows the pattern for Draft EAS to set up basic tests for Technical Memo (note that it does not yet include tests for submit and show page, since those do not yet exist)
Contributes towards fixing [AB#13209](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13209)
- Turns out I previously forgot to include Projects with active Technical Memo underneath "Awaiting Submission". These tests helped reveal that. :)

13209 Sets up basic tests for technical memo

---

client/app/components/packages/technical-memo/edit.hbs
client/app/components/packages/technical-memo/edit.js
client/app/components/packages/technical-memo/show.hbs
client/app/components/packages/technical-memo/technical-memo-error.hbs
client/app/templates/technical-memo/show.hbs
client/tests/acceptance/user-can-edit-technical-memo-test.js

Follows pattern of Draft EAS to set up the Tech Memo Submission and Show Page. Sets up the corresponding tests, as well.
Fixes [AB#13056](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13056)
Fixes [AB#13064](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13064)
Contributes to [AB#13209](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13209)

13056 13064 Set up Tech Memo Submit and Show page

---

client/app/components/packages/filed-eas/edit.hbs
client/app/components/packages/filed-eas/edit.js
client/app/components/packages/filed-eas/filed-eas-error.hbs
client/app/components/packages/filed-eas/show.hbs
client/app/templates/filed-eas/show.hbs
client/tests/acceptance/user-can-edit-filed-eas-test.js

Follows the pattern for Draft EAS to set up Submission and Show page for Filed EAS.
Fixes [AB#13041](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13041)
Fixes [AB#13042](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13042)
Contributes to [AB#13209](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13209)
- The tests revealed that `client/app/templates/filed-eas/show.hbs` incorrectly referenced the package, so this PR patches that as well.

13041 13042 Submission and Show page for Filed EAS

---

server/src/document/document.controller.ts
server/src/document/document.service.ts

The problem is that a recent CRM enhancement changed the format for Sharepoint Folder names, so it differed from the format Applicant Portal used. 
To match the new version used for **version 1** folder names, we remove hyphens from the Package Id component of the folder name.
**However, the second and subsequent versions have yet another different format. Unlike the first version, the Package Name portion removes underscores, and the Package ID section _includes_ Package IDs.**
**It is on CRM to fix this issue with second revisions.** 
Potential fix for [AB#12489](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12489)

12489 Standby patch to remove hyphens from PackageId portion of Sharepoint folder names

---

client/app/components/packages/deis/attached-documents.hbs
client/app/components/packages/deis/edit.hbs
client/app/components/packages/deis/edit.js
client/app/components/packages/draft-eas/attached-documents.hbs
client/app/components/packages/draft-eas/edit.hbs
client/app/components/packages/draft-eas/edit.js
client/app/components/packages/feis/attached-documents.hbs
client/app/components/packages/feis/edit.hbs
client/app/components/packages/feis/edit.js
client/app/components/packages/filed-eas/attached-documents.hbs
client/app/components/packages/filed-eas/edit.hbs
client/app/components/packages/filed-eas/edit.js
client/app/components/packages/scope-of-work-draft/attached-documents.hbs
client/app/components/packages/scope-of-work-draft/edit.hbs
client/app/components/packages/scope-of-work-draft/edit.js
client/app/components/packages/technical-memo/attached-documents.hbs
client/app/components/packages/technical-memo/edit.hbs
client/app/components/packages/technical-memo/edit.js

I incorrectly (showed @CeciliaCY how to) set up the Attachments section for the Draft EAS, Filed EAS, DEIS, FEIS, Tech Memo and DSOW sections. I needed to add a Submittable Package Validation to ensure that users upload at least one document before they can submit.  As shown in PR #836 
Fixes [AB#13266](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13266)

13266 Add SubmittablePackageValidation for DEAS, FEAS, DEIS, FEIS, Tech Memo, DSOW

---

client/app/components/ui/breadcrumbs-item.hbs
client/app/templates/deis/edit.hbs
client/app/templates/deis/show.hbs
client/app/templates/draft-eas/edit.hbs
client/app/templates/draft-eas/show.hbs
client/app/templates/feis/edit.hbs
client/app/templates/feis/show.hbs
client/app/templates/filed-eas/edit.hbs
client/app/templates/filed-eas/show.hbs
client/app/templates/landuse-form/edit.hbs
client/app/templates/landuse-form/show.hbs
client/app/templates/pas-form/edit.hbs
client/app/templates/pas-form/show.hbs
client/app/templates/rwcds-form/edit.hbs
client/app/templates/rwcds-form/show.hbs
client/app/templates/scope-of-work-draft/edit.hbs
client/app/templates/scope-of-work-draft/show.hbs
client/app/templates/technical-memo/edit.hbs
client/app/templates/technical-memo/show.hbs
client/app/templates/working-package/edit.hbs
client/app/templates/working-package/show.hbs

This PR activates the "Project" crumb for Edit and Show pages
Previously, on the Edit or Show page, the breadcrumb for the individual project page was deactivated. This meant that to navigate back up to the Project page, using the application navigation someone had to first return to My Projects and then click the concerned project. This was inconvenient especially if the user directly loads a package (pasting into the browser a Package url like `/rwcds-form/12341234/edit`), since then the back button isn't available.
This change gets rid of an annoyance and helps speed up development time a bit :) 
Fixes [AB#13297](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13297)

Activate "Project" crumb for Edit and Show pages

---

client/app/components/packages/landuse-form/edit.hbs

13282 Addressing Confirmation prompt saying Draft LU instead of Filed LU
Fixes AB#[13282](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/13282)
Add if condition to show draft and file depending on dcpPackagetype

13282 Addressing Confirmation prompt saying Draft LU instead of Filed LU

---

client/app/components/packages/landuse-form/show.hbs

13231 Add Navigation to Land Use Show
Fixes [AB#13231](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/13231)
Add <SaveableForm> to enable <saveableForm.PageNav> on this page

13231 Add Navigation to Land Use Show

---

client/app/components/packages/filed-eas/ceqr-invoice-questionnaire.hbs
client/app/components/packages/filed-eas/edit.hbs
client/app/components/packages/filed-eas/edit.js
client/app/helpers/optionset.js
client/app/models/ceqr-invoice-questionnaire.js
client/app/models/package.js
client/app/optionsets/ceqr-invoice-questionnaire.js
client/app/optionsets/common.js
client/app/routes/filed-eas.js
client/app/validations/submittable-ceqr-invoice-questionnaire-form.js
client/mirage/config.js
client/mirage/factories/package.js
client/mirage/models/ceqr-invoice-questionnaire.js
client/mirage/models/package.js
client/tests/acceptance/user-can-edit-filed-eas-test.js
server/src/json-api-deserialize.pipe.ts
server/src/packages/ceqr-invoice-questionnaires/ceqr-invoice-questionnaires.attrs.ts
server/src/packages/ceqr-invoice-questionnaires/ceqr-invoice-questionnaires.controller.ts
server/src/packages/packages.controller.ts
server/src/packages/packages.module.ts
server/src/packages/packages.service.ts

**Summary**
Add Ceqr Invoice Questionnaire section to Filed Eas Package.
**Task/Bug Number**
[AB#13037](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13037)
**Technical Explanation**
- create new `ceqr-invoice-questionnaire` component that is rendered on the `filed-eas/edit.hbs` component
- because the questionnaire is stored in a separate entity, use `$expand` on the package GETter to include the ceqr-invoice-questionnaire
- users can PATCH to the ceqr-invoice-questionnaire fields

13037: add ceqr questionnaire to filed eas package

---

client/app/components/packages/landuse-form/proposed-action-editor.hbs
client/app/components/packages/related-action-fieldset.hbs
client/tests/acceptance/user-can-click-landuse-form-edit-test.js
server/src/json-api-deserialize.pipe.ts
server/src/packages/landuse-form/landuse-actions/landuse-actions.attrs.ts
server/src/packages/landuse-form/landuse-actions/landuse-actions.controller.ts
server/src/packages/landuse-form/landuse-form.service.ts
server/src/packages/landuse-form/related-actions/related-actions.attrs.ts
server/src/packages/landuse-form/related-actions/related-actions.controller.ts
server/src/packages/packages.controller.ts

**Summary**
Implement date-picker component on the Related Actions and Proposed Actions sections on the Land Use Form.
**Task/Bug Number**
[AB#12712](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12712)
**Technical Explanation**
- Implement Ember Flatpicker component throughout the landuse-form. All styling was previously addressed by Andy. 
- When the date value is sent to the backend, it shows up in the body formatted as a date-string within an array. Because of this I had to reformat the date in the related-actions.controller and landuse-actions.controller. Otherwise CRM will throw an error claiming that the date is formatted incorrectly.
**Open to suggestions on how to better go about this formatting issue!**

12712: update  date fields on landuse-form to include  new date-picker component

---

client/app/models/invoice.js
client/app/templates/invoice.hbs
server/src/invoices/invoices.attrs.ts
server/src/invoices/invoices.controller.ts
server/src/invoices/invoices.service.ts

Fixes the issue by using the correct, "real" attribute names as they're named on the invoice entity.
Includes the line items of the invoice using an expand. Avoids using a model and simply provides a read-only array of line items. 
Applies the overwriteValuesWithLabels helper to get neater naming for each value.
Fixes [AB#13298](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13298)

Use correct attr names for entity; join in labels; iterate line items

---

client/app/components/project/package-section.hbs
client/app/components/project/package-section.js
client/app/components/project/package-section/invoice-info.hbs
client/app/models/invoice.js
client/ember-cli-build.js
client/tests/integration/components/project/package-section/invoice-info-test.js
server/src/invoices/invoices.attrs.ts
server/src/invoices/invoices.service.ts
server/src/projects/projects.service.ts

Show checkmark icon when paid
- Modifies the filtering logic for invoices a little to allow for paid or approved invoices
- include the statuscode attribute on invoices for icons and filtering
- hide pay button when no payable invoices exist
Fixes [AB#13299](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13299)

Fix invoice filter logic; hide pay button when no invoices need payment

---

client/app/components/project/package-section.hbs
client/app/components/project/package-section.js
client/app/components/project/package-section/invoice-info.hbs
client/app/helpers/to-locale-string.js
client/app/models/package.js
client/app/routes/invoice.js
client/tests/integration/helpers/to-locale-string-test.js
server/src/_utils/overwrite-codes-with-labels.ts
server/src/invoices/invoices.service.ts
server/src/projects/projects.controller.ts
server/src/projects/projects.service.ts

Small changes to force reload of the invoice route. Before, it was only getting a partial fragment of the invoice from a previous route, and using that fragment to render the view. This change forces a reload of the entire entity.
Fixes [AB#13298](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13298)
Includes bug fix in which "hasPayableInvoice" computed was not calculating correctly because of the nature of ember data's hasMany relationships

Force reload entire invoice; format raw values

---

client/app/components/packages/applicant-fieldset.hbs
client/app/components/packages/landuse-form/lead-agency.hbs
client/app/components/packages/landuse-form/lead-agency.js
client/app/components/packages/landuse-form/proposed-action-editor.hbs
client/app/components/packages/landuse-form/proposed-action-editor.js
client/app/components/packages/landuse-form/zoning-map-amendment-fieldset.hbs
client/app/components/packages/landuse-form/zoning-map-amendment.hbs
client/app/components/packages/landuse-form/zoning-resolution-dropdown.hbs
client/app/components/packages/landuse-form/zoning-resolution-dropdown.js
client/app/styles/app.scss
client/app/styles/modules/_powerselect-overrides.scss
server/src/crm/crm.service.ts
server/src/packages/landuse-form/landuse-actions/landuse-actions.controller.ts
server/src/packages/landuse-form/landuse-form.controller.ts

Allows users to clear the dropdown selection on the Land Use Form Page. Including for these questions:
1 PAS/RWCDS/Land Use Form > applicant geographic state
2 Land Use Form > Zoning Map Amendments section > Total Area of All Zoning Lots
3 Land Use Form > Zoning Map Amendments section > Existing Zoning District
4. Land Use Form > Environmental Review section > Lead Agency
5. Land Use Form > Proposed Actions section > Previously Approved Action code
6. Land Use Form > Proposed Actions section > Zoning Resolution action is Pursuant to
Fixes [AB#13309](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13309)
- For questions 1-3 above, the solution was simply to set the `@allowClear={{true}}` argument on the Power Selects. This enables a Power Select …

13309 Add ability to clear LU form dropdowns

---

client/app/components/packages/landuse-form/proposed-action-editor.hbs
client/app/components/packages/landuse-form/show.hbs
client/app/models/landuse-action.js
client/app/validations/saveable-landuse-action-form.js
server/src/packages/landuse-form/landuse-actions/landuse-actions.attrs.ts

Fixes [AB#13352](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13352)
Changed from dcp_zoningresolutionsectionactionispursuant to dcp_zoningsectionstobemodified for the "Zoning Resolution section(s) to be modified" field.

13352 - Updated variable name

---

server/src/projects/projects.controller.ts
server/src/projects/projects.service.ts

The controller serializer was handling munging for everything. This was excluding certain munging necessary for project-specific requests.
This change makes the service responsible for each serialization needed. For example, the /projects view needs to code packages correctly. But projects/:id includes a lot more info.
Fixes [AB#13299](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13299)

Remove serializer transform; put logic in service

---

client/app/components/packages/working-package/edit.js
client/app/components/packages/working-package/show.hbs

Fix submit button not working when trying to submit the working package
Fixes [AB#13370](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/13370)
submitPackage() was missing in the edit.js, so added it back.
Show page was empty, so copy paste related code there.

Fix submit button not working when trying to submit the working package

---

client/app/components/packages/landuse-form/show.hbs

On the Land Use Form Show page, conditionally displays  the From and To questions if Manner of Dispo is "Direct". 
Fixes [AB#12777](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12777)

12777 Fix support for missing manner of dispo. answers.

---

client/app/components/packages/ceqr-invoice-questionnaire.hbs
client/app/components/packages/filed-eas/edit.hbs
client/app/components/packages/filed-eas/edit.js
client/app/components/packages/scope-of-work-draft/edit.hbs
client/app/components/packages/scope-of-work-draft/edit.js
client/app/validations/submittable-ceqr-invoice-questionnaire-form.js
client/tests/acceptance/user-can-edit-filed-eas-test.js
server/src/packages/ceqr-invoice-questionnaires/ceqr-invoice-questionnaires.controller.ts

**Remove the automatic creation** of a new ceqr invoice questionnaire every time the user visits the package page. This was implemented before an enhancement in CRM made it obsolete. 
Add **new conditional logic** to the Ceqr Invoice Questionnaire section
- All questions below will only show up if "Is the sole applicant a government agency (City, State, or Federal)?" is checked "No"
- the "What is the Square Footage of the Total Project?" question will only show up if the answer to "Does your project solely consist of action(s) that are not measureable by sq. ft.?" is "No"
Fixes [AB#13396](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13396), [AB#13397](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/ …

13396: update conditional logic on ceqr-invoice-questionnaire

---

client/app/components/packages/filed-eas/show.hbs

13394 Display the CEQR Questionnaire on the submitted Filed EAS form
Fixes [AB#13394](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/13394)
Add CEQR section in show.hbs based on edit.hbs. Also add SaveableForm to enable dynamic nav on the right.

13394 Display the CEQR Questionnaire on the submitted Filed EAS form

---

server/src/document/document.controller.ts
server/src/document/document.service.ts

After Sprint 10, it sounds like Microsoft consultants are moving towards just using the raw `dcp_name` property to create the Sharepoint Folder name. Waiting for confirmation.
Fixes [AB#12715](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12715)
- After Sprint 10 CRM enhancements, App Portal should no longer need to remove spaces and dashes from `dcp_name`
- We are removing the apostrophe replacement because after Sprint 10 CRM enhancements, the raw `dcp_name` value should be used to generate the sharepoint folder name.
- We are removing the special character replacement (`.replace(/^\~|\#|\%|\&|\*|\{|\}|\\|\:|\<|\>|\?|\/|\||\"/g, '');`) because supposedly there should no longer be any special characters in package names. The `dcp_name` …

Assume Sharepoint Folder name uses raw Package Name

---

client/app/components/packages/filed-eas/show.hbs
client/app/components/packages/scope-of-work-draft/show.hbs
client/tests/acceptance/user-can-edit-filed-eas-test.js
client/tests/acceptance/user-can-edit-scope-of-work-draft-test.js

13386 Display the CEQR Questionnaire on the submitted DSOW form
[Fixes AB#13386](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/13386)
Add CEQR section in show.hbs based on edit.hbs. Also add SaveableForm to enable dynamic nav on the right. Similar to #895

13386 Add CEQR to DSOW show page

---

client/app/components/packages/ceqr-invoice-questionnaire.hbs
client/app/helpers/square-footage-to-subtotal.js
client/app/models/ceqr-invoice-questionnaire.js
client/tests/integration/helpers/square-footage-to-subtotal-test.js
server/src/packages/ceqr-invoice-questionnaires/ceqr-invoice-questionnaires.attrs.ts

When a user selects a square footage value range (`dcpSquarefeet`) in the dropdown on the Ceqr Invoice Questionnaire, the subtotal field (`dcpSubtotal`) should be updated based on the square footage value. 
Fixes [AB#13515](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13515)
- a function for mutating the `dcpSubtotal` field on the `dcp_ceqrinvoicequestionnaire` entity was added using the `@onClose` tag for the ember-power-select dropdown
- A lookup was needed to set the correct value on `dcpSubtotal` depending on what the user chose for the square footage value. This lookup was stored in a helper called `square-footage-to-subtotal`. This helper employed the use of the `dcpSquarefeet` optionset

13515: update subtotal value on ceqr invoice questionnaire based on square footage value

---

client/app/components/project/milestones/milestone-group-item.hbs

13524 small fix to 13524: rename to showTheProject to showProject
[Fixes AB#13524](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/13524)
Rename to showTheProject to showProject

13524 small fix to 13524 rename to showProject

---

client/app/components/packages/ceqr-invoice-questionnaire.hbs
client/app/components/packages/ceqr-invoice-questionnaire.js

Update the logic for setting the subtotal value on the Ceqr Invoice Questionnaire. When a user answers the question "Does the project consist solely of modification actions that are not subject to 197c?" with `No`, the subtotal is set based on the value mapping between square footage and subtotal. When the user answers `Yes` to the above question, the subtotal is 20% of the original value. (e.g. $460 --> $92)
Fixes [AB#13515](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13515)
This PR updates the function that is run on the `onClose` tag for the `dcpSquarefeet` dropdown as well as adds a function to the `onChange` tag for the `dcpProjectmodificationtoapreviousapproval` radio buttons. This function sets the `dcpSubtotal` value differently …

13515: update logic for setting subtotal on ceqr-invoice-questionnaire

---

client/app/components/packages/landuse-form/edit.js
client/app/components/packages/landuse-form/proposed-actions.hbs
client/app/models/landuse-action.js
client/app/validations/saveable-landuse-action-form.js

- CRM requires 5 of the Proposed Actions fields to be Integers, not strings. Previously they were sent to the backend as strings and yielding an error on Save.
-  The validations for the Proposed Actions form were not set up properly. This PR sets up the validations properly.
Fixes [AB#13570](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13570)

13570 Fix (number) validations for Proposed Actions

---

client/app/components/project/milestones/milestone-group-item.hbs
client/app/components/project/milestones/milestone-group.hbs
client/app/components/project/milestones/milestone-group.js
server/src/projects/projects.attrs.ts
server/src/projects/projects.service.ts

Make sure that milestones list on the individual project page are sorted by Planned Start Date for "Not Started" milestones and by Actual Start Date for milestones that are "In Progress" or "Completed"
Fixes [AB#13527](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13527)
- Previously we were reformatting all fields from `dcp_projectmilestone` entity. This caused four date fields to be reformatted into strings when sent to the frontend. This PR removes this reformatting so that the dates in the frontend are formatted as dates. We then instead use `date-display` helper to reformat them to strings for display purposes on the template. 
- A new computed property was added called `sortedGroupedMilestones` which sorts the milestones based off of …

13527: remove the reformatting of dates into strings for milestones to allow for sorting

---

client/app/models/project.js
client/app/optionsets/project.js

There was recently an update in CRM that changed the label for `dcpPublicstatus` from "Prefiled" to "Noticed". This PR implements that change in the app
Fixes [AB#13591](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13591)

13591: update dcpPublicstatus label from Prefiled to Noticed to match CRM

---

client/app/components/packages/rwcds-form/with-action-no-action.hbs
client/app/validations/saveable-rwcds-form.js
client/tests/acceptance/user-can-click-rwcds-form-edit-test.js

Set maxlength of the RWCDS Form's dcpHowdidyoudeterminethenoactionscenario property to 600 to match CRM
TBA

set maxlength of dcpHowdidyoudeterminethenoactionscenario to 600

---

client/app/adapters/application.js
client/app/adapters/package.js
client/app/components/packages/deis/deis-error.hbs
client/app/components/packages/deis/edit.js
client/app/components/packages/draft-eas/draft-eas-error.hbs
client/app/components/packages/draft-eas/edit.js
client/app/components/packages/error.hbs
client/app/components/packages/feis/edit.js
client/app/components/packages/feis/feis-error.hbs
client/app/components/packages/filed-eas/edit.js
client/app/components/packages/filed-eas/filed-eas-error.hbs
client/app/components/packages/landuse-form/edit.js
client/app/components/packages/landuse-form/landuse-form-error.hbs
client/app/components/packages/pas-form/edit.js
client/app/components/packages/pas-form/pas-form-error.hbs
client/app/components/packages/rwcds-form/edit.js
client/app/components/packages/rwcds-form/rwcds-form-error.hbs
client/app/components/packages/scope-of-work-draft/edit.js
client/app/components/packages/scope-of-work-draft/scope-of-work-draft-error.hbs
client/app/components/packages/technical-memo/edit.js
client/app/components/packages/technical-memo/technical-memo-error.hbs
client/app/components/packages/working-package/edit.js
client/app/models/package.js
client/mirage/config.js

The Save and Submit functionality faced a couple problems, which needed to be teased apart:
1.  **The attachments component is adding `filesToUpload` files to the `package.documents` array.** This is likely due to the need to validate the number of documents to upload ( >= 1), but can cause problems if a package is saved and the documents property is serialized. When the user selects files for upload, they are represented as `ember-file-upload` `fileQueue` objects. These complex fileQueue objects are being added to the `package.documents` array alongside our custom document objects (simply consisting of `name`, `timeCreated`, and `relativeUrl` properties). When the `fileQueue` objects are serialized, they error out because these objects are recursive.
The error yielded is `TypeError: …

13578 Improve Save and Submit UX and implementation 

---

client/app/helpers/optionset.js

Fixes AB#790
Previously, whenever a `null` was passed to an optionset helper, it would throw an alarming red error message in our console, even if it is OK. This PR changes the message to just warnings.
For one optionset, `null` is a valid option. For others, `nulls` are unavoidable simply because a lot of the model properties start as `null`. 
**Before:**
**Now:**

790 Display optionset warning instead of assertion error

---

client/app/components/packages/applicant-fieldset.hbs
client/app/components/packages/landuse-form/primary-contact.hbs
client/app/validations/saveable-applicant-form.js
client/app/validations/saveable-landuse-form.js
client/tests/acceptance/pas-form-validation-messages-display-test.js

Phone number fields (e.g. `dcpContactphone` on the landuse entity and `dcp_phone` on the applicant entity) are stored as strings in CRM. When the user includes dashes in their phone number entry, the input will not save to the database. Unfortunately, the validation addon that we use stops working when the user includes a dash in the input -- the validation message disappears and the user can then type as many numbers as they want.
In order to avoid this, this PR has:
- added a `regex` field to the validation that matches a 10 digit phone number with only numbers (and no special characters)
- changed the input type of the field to be `text` because for some reason the hyphen issue was only happening when the input type was `number`. This is a drawback because the user can now enter …

771: validation message appears if user includes dashes in phone numbers

---

client/app/components/packages/applicant-fieldset.hbs
client/app/components/packages/landuse-form/proposed-site-characteristics-fieldset.hbs
client/app/components/packages/landuse-form/subject-sites-fieldset.hbs
client/app/components/packages/landuse-form/zoning-map-amendment-fieldset.hbs
client/app/components/packages/landuse-form/zoning-text-amendment-fieldset.hbs
client/app/components/packages/related-action-fieldset.hbs

The `*-fieldset.hbs` files were passing an unnecessary extra argument to already "fully applied" `@remove*` actions. The remove actions only take two arguments, and parent component of these fieldsets already passed those two arguments.
Fixes AB#768

768 Remove unnecessary argument to remove* actions in landuseForm *-fieldsets

---

client/app/components/auth/sign-in.js
server/src/contact/nycid/nycid.service.ts

If a user is a City Employee they should be redirected to the NYC.ID sign-in page regardless of their NYC ID registration status. This PR updates the rerouting logic to always send City Employees to the sign-in page. 
Just noting some extra information for documentation & research purposes based on email exchange with NYC.ID folks: 
- They confirmed that a city employee will NEVER register on the "register" page that we were originally sending non-registered city employees to. Instead they should always be redirected to the NYC.ID login page where they can select the NYC Employee option button. More information at https://www1.nyc.gov/assets/nyc4d/html/services-nycid/registration.shtml 
- They suggested that we use `GET /account/api/oauth/user.htm` instead of `GET', …

777: redirect city employees to nyc.id sign-in page regardless of registration status

---

client/config/environment.js
client/mirage/config.js

I redeployed Search API onto Heroku because it was still on Labs-01 Dokku. This PR updates the Search API endpoint to reflect this change.
- Fixes AB#1234 https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/804/

Point Search API domain to new heroku-based deployment

---

client/app/routes/auth/sync.js

After a user clicks on the "NYC.ID Profile" button, they are taken to an NYCID-managed page where they can edit their NYCID profile information. 
If they click "Back" or "Submit" on that page, they are taken back to the root auth route of applicant portal
This is incorrect behavior, and instead it should reroute them to the user's projects page. 
This PR makes sure the correct reroute happens.
- Fixes [AB#858](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/858)
Previously, in `client/app/routes/auth/sync.js` the model hook assumes if a user returns from NYCID, the `window.document.referrer` value contains the subroute and query parameters when on NYCID (e.g. "/account/user/profile.htm?returnOnSave=true"). However, upon my inspection it only contains …

858 fix redirect to /projects on return from nycid

---

client/app/components/packages/landuse-form/project-information.hbs
client/app/models/landuse-form.js
client/app/validations/saveable-landuse-form.js
client/tests/acceptance/user-can-click-landuse-form-edit-test.js

Update the Project Name field on the Land Use Form to point to `dcpSitedataprojectname` field on the landuse-form entity rather than the `dcp_projectname` field on the project entity. 
Addresses [AB#1309](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/1309)
The field on the project entity`dcp_projectname` gets automatically updated once the `dcp_sitedataprojectname` on the landuse-form entity is saved in CRM. Therefore Labs would not have to do any "copying over" of the data from one field to another on our end.

1309: update project name input on landuse form to point to dcpSitedataprojectname

---

client/app/services/file-manager.js

This prevents multiple requests to /documents at once. This gives the first ping of /documents to rename an existing Sharepoint folder, if necessary.

2102 Synchronously upload files one at a time

---

client/app/components/packages/landuse-form/environmental-review.hbs

User is now able to see the "What is the Type II Category " question if and only if he/she selects "Type II" from the "What is the CEQR type?" Question 
- Fixes [AB#1709](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/1709)

Made question appear only when conditions are met

---

client/app/components/packages/applicant-fieldset.hbs
client/app/validations/saveable-applicant-form.js

Added character limits to the organization name fields.
- Fixes [AB#1710](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/1710)

Implemented character limits on organization name fields

---

client/app/components/project/package-list-item.hbs
client/app/models/package.js
server/src/packages/packages.attrs.ts

Fixes [AB#2787](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2787)

2787 Display submission date for inactive, post-submission packages

---

client/app/components/project/package-list-item.hbs
client/tests/integration/components/project/package-list-item-test.js

Fixes [AB#2786](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2786)
┆Issue is synchronized with this [Azure issue](https://dev.azure.com/dcp-paperless/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13812/) by [Unito](https://www.unito.io)

2786 Always display Editable and statusdate for active packages

---

client/app/components/project/package-list-item.hbs
client/app/models/package.js
client/app/models/project.js
client/app/optionsets/package.js
client/app/templates/landuse-form/edit.hbs
client/app/templates/landuse-form/show.hbs
server/src/packages/packages.service.ts

Fixes [AB#2785](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2785)
Follows pattern of Draft and Filed LU packages to set up Post-Cert Land Use Package

2785 Set up Post Cert LU Package

---

client/app/components/packages/landuse-form/show.hbs
client/app/components/packages/landuse-form/zoning-map-amendment-fieldset.hbs
client/app/helpers/optionset.js
client/app/models/zoning-map-change.js
client/app/validations/saveable-zoning-map-change.js
client/tests/acceptance/user-can-click-landuse-form-edit-test.js
server/src/packages/landuse-form/zoning-map-changes/zoning-map-change.attrs.ts

Updates variable name and input field to prepare for CRM update.
Closes [AB#2784](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2784)

2784 Applicant Portal LU Form: Update field type for Existing Zoning Districts field under Zoning Map Amendment

---

client/app/components/packages/rwcds-form/project-description.hbs
client/app/validations/saveable-rwcds-form.js
client/tests/acceptance/user-can-click-rwcds-form-edit-test.js

- update dcpProposedprojectdevelopmentdescription field from 1800 to 2400 characters
- update tests with new character limit
- Fixes [AB#8205](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8205)

8205 - increase char limit in dcpProposedprojectdevelopmentdescription field

---

client/app/components/packages/rwcds-form/with-action-no-action.hbs
client/app/validations/saveable-rwcds-form.js
client/tests/acceptance/user-can-click-rwcds-form-edit-test.js

- update char limit for dcpRwcdsexplanation data field from 50 to 2400 
- update tests to reflect higher char limit
- update gitignore to include all DS_Store
- adjust heading in README.md
- Fixes [AB#8204](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8204)

8204 increase char limit for dcpRwcdsexplanation data field

---

client/app/components/packages/rwcds-form/project-description.hbs
client/app/validations/saveable-rwcds-form.js
client/tests/acceptance/user-can-click-rwcds-form-edit-test.js

- update dcpRationalbehindthebuildyear field from 300 to 2400 characters
- update tests with new character limit
- Fixes [AB#8206](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8206)

8606 increase char limit for the dcpRationalbehindthebuildyear field

---

client/app/components/packages/landuse-form/project-area.hbs
client/app/validations/saveable-landuse-form.js
client/tests/acceptance/user-can-click-landuse-form-edit-test.js

- increased character limit for the dcpSitedatarenewalarea field
- added test for dcpSitedatarenewalarea input field maximum
- updated test max char amount
- Fixes [AB#8203](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8203)

8203 incr char limits for Historic District Name

---

client/app/components/packages/rwcds-form/project-description.hbs
client/app/validations/saveable-rwcds-form.js
client/tests/acceptance/user-can-click-rwcds-form-edit-test.js

- increased limits for dcpSitehistory input from 600 to 2400 characters, 
- updated char limits in tests
- Fixes [AB#8207](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8207)

8207 increase  char limit for dcpSitehistory input field

---

client/app/components/packages/rwcds-form/proposed-project-actions.hbs
client/app/validations/saveable-rwcds-form.js
client/tests/acceptance/user-can-click-rwcds-form-edit-test.js

- increased limits for dcpPurposeandneedfortheproposedaction input field from 1500 - 2400 characters
- updated char limits in tests
- Fixes [AB#8208](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8208)

8208 incr char limits for dcpPurposeandneedfortheproposedaction

---

client/app/components/packages/rwcds-form/with-action-no-action.hbs
client/app/validations/saveable-rwcds-form.js
client/tests/acceptance/user-can-click-rwcds-form-edit-test.js

- increased limits for dcpDevelopmentsiteassumptions input field from 2400 to 4800 characters
- updated char limits in tests
- Fixes [AB#8209](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8209)

8209 incr char limits for dcpDevelopmentsiteassumptions

---

client/app/components/packages/landuse-form/subject-sites-fieldset.hbs
client/app/validations/saveable-sitedatah-form.js
client/tests/acceptance/user-can-click-landuse-form-edit-test.js

- increased limits for dcpLotnumberstring input field from 100 to 250 characters 
- updated char limits in validation from 20 to 250
- add test for validation of char max length
- Fixes [AB#8202](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8202)

8202 incr char limits for dcpLotnumberstring 

---

client/app/components/packages/landuse-form/proposed-action-editor.hbs
client/app/components/packages/landuse-form/show.hbs
client/app/models/landuse-action.js
client/app/validations/saveable-landuse-action-form.js
server/src/packages/landuse-form/landuse-actions/landuse-actions.attrs.ts

- Add the conditional field "Previously Approved Application Number(s)  to the Applicant portal Land Use form under the Proposed Actions section.
- Display the question as "If this is a follow-up Action, indicate the ULURP or CP number of previous approval"
- When "If this is a follow-up Action, indicate the previously approved Action Code [dcp_previouslyapprovedactioncode]" (field A) is not Null, display conditional question for dcp_previouslyapprovedapplicationnumbers directly below (field A).
- The "If this is a follow-up Action, indicate the ULURP or CP number of previous approval" field must be:
- Text
- Length: 100
- Not required
- Default to null
- Fixes [AB#8201](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8201)
- Related …

8201 add conditional form field previously approved application number to LU form

---

client/app/components/packages/rwcds-form/with-action-no-action.hbs
client/app/validations/saveable-rwcds-form.js
client/tests/acceptance/user-can-click-rwcds-form-edit-test.js

- dcpDescribethenoactionscenario input field
- input validation 
- input test
from from 1500 characters to 2400.
- Fixes [AB#8312](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8312)
- Related [AB#2240](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2240)

8312 update char limits of Description of No-Action Scenario input

---

client/app/components/packages/rwcds-form/with-action-no-action.hbs
client/app/validations/saveable-rwcds-form.js
client/tests/acceptance/user-can-click-rwcds-form-edit-test.js

increase the char limit from 1500 to 2400 
- for the dcpDescribethewithactionscenario input 
- update validation with the new max limit
- update test with the new max limit
- Fixes #1042 
- Related #2244

8307 increase the char limit for the dcpDescribethewithactionscenario input

---

client/app/components/packages/equitable-development-reporting.hbs

updated copy in PAS Racial Equity Section line 38 from "New residential building of 50,000 sf or more" to "to facilitate a new, enlarged, or converted residential building of 50,000 zoning square feet or more"
- Fixes [AB#8515](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8515)

8515 updated copy in PAS Racial Equity Section for greater clarity

---

client/app/components/packages/equitable-development-reporting.hbs
client/app/styles/app.scss

Add the below text as additional guidance under question “Increase permitted non-residential floor area by at least 200,000 square feet”
- utilized svg and tooltip as per gilal designs in figma
Additional copy added in the `equitable-development-reporting.hbs` file
- Fixes [AB#8426](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8426)

8426 added guidance copy to PAS equity form below non-res fl area 200K

---

client/app/components/packages/equitable-development-reporting.hbs

Add the below text as additional guidance under question “Increase permitted residential floor area by at least 50,000 square feet”
additional copy added in the `equitable-development-reporting.hbs` file
- Fixes [AB#8420](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8420)

8420 added guidance copy to PAS equity form 

---

client/app/components/packages/equitable-development-reporting.hbs

PAS Racial Equity Section: additional guidance under question “Decrease permitted residential floor area on at least four contiguous city blocks”:

8427 addl copy added after Decrease permitted residential floor area

---

client/app/components/packages/rwcds-form/with-action-no-action.hbs

update copy in Applicant RWCDS Form  referring to CEQR tech manual from `Chapter 2, (page2-5, 2-6, &amp; 2-7)`  to  `Chapter 2, (pages 2-7, 2-8, 2-9, 2-10)`.
- Fixes [AB#8489](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8489)
- Related [AB#2246](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2246)
- Reverses [AB#8305](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8305)

8489 update copy in RWCDS form to reference correct pgs in CEQR manual

---

client/app/components/packages/equitable-development-reporting.hbs

add tootip to pas equity section after decrease permitted floor area omitted in #1057 
- Fixes [AB#8575](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8575)
- Related [AB#8427](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8427)
- Parent  [AB#8374](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8374)
-

8575 add tooltip omitted in ADO #8427

---

client/app/components/packages/equitable-development-reporting.hbs
client/app/styles/app.scss

Add'l guidance to PAS Racial Equity Section below “I am applying for a Special Permit (ZS, RS), Zoning Map Amendment (ZM) and/or a Zoning Text Amendment (ZR)"
- update question copy
- update note below question copy
- implement tooltip for additional guidance / clarification copy
- adjust tooltip width to 320px from 200px to match Figma designs
- Fixes [AB#8433](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8433)

8433 addl guidance copy to PAS equity section with tooltip

---

client/app/components/packages/equitable-development-reporting.hbs

housekeeping and cleanup for applicant portal tasks
- updated copy from "at least 50,000 sf floor area" to "at least 50,000 zoning square feet floor area"
- updated copy from "square feet" to  "zoning square feet"  for both "Increase permitted residential floor area" and "Increase permitted non-residential floor area".
- tooltips updated to two paragraphs for both "Increase permitted residential floor area" and "Increase permitted non-residential floor area",
- updated copy from ZSF to zoning square feet for "Increase permitted residential floor area" and "Decrease permitted residential floor area"
- Fixes [AB#8579](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8579)

8578 housekeeping and cleanup for applicant portal tasks

---

client/app/components/packages/equitable-development-reporting.hbs
client/app/components/packages/landuse-form/show.hbs
client/app/components/packages/pas-form/show.hbs

See line 3 in client/app/components/packages/equitable-development-reporting.hbs
<form.Section @title="Equitable Development Reporting">
Update the new EDDE (Equitable Development Reporting) section header on the PAS form to "Racial Equity Report".
Update the associated navigation title on the PAS form to Racial Equity Report.
Update the new EDDE (Equitable Development Reporting) section header on the LU form to "Racial Equity Report".
Update the associated navigation title on the LU form to Racial Equity Report.
Update the blurb under the revised header to: 
- Completes [AB#8613](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8613)

8613 Update EDDE section headers

---

client/app/components/packages/equitable-development-reporting.hbs
client/app/styles/app.scss

on PAS and LU forms
Updated copy of auto response to:  ‘Subject to Racial Equity Report’ Auto-Response to Equitable Development questions on PAS and Land Use form
- Fixes [AB#8617](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8617)
- Related [AB#7024](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/7024)
-

auto response copy for ‘not subject to racial equity report' to racial equity section questions

---

client/app/components/packages/equitable-development-reporting.hbs

Update copy for auto-response for ‘Subject to Racial Equity Report’ to Equitable Development questions on PAS and Land Use form
- Fixes [AB#8623](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8623)

auto response copy update for ‘subject to racial equity report' to racial equity section questions

---

client/app/components/packages/attachments.hbs
client/app/components/packages/deis/attached-documents.hbs
client/app/components/packages/feis/attached-documents.hbs

The file limit is implemented on the sharepoint side and has already been updated.  This simply updates the site text to reflect the limit.
- Completes [AB#8334](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8334)

8334 Limit file uploads to 100mb. 

---

client/app/components/packages/equitable-development-reporting.hbs

cleaned up some copy that was not meant to be included.
- Fixes [AB#8650](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8650)
- Related [AB#8617](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8617)

8650 removed unnecessary copy from auto response in racial equity section

---

client/app/components/packages/equitable-development-reporting.hbs

- Fixes [AB#8735](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8735)

8735 correct copy for tooltip, update local law link to document

---

client/app/components/packages/equitable-development-reporting.hbs

Correct copy from `Proposed change in permitted zoning square feet (residential)` to `Change in permitted zoning square feet (non-residential)` in the tooltip for `Increase permitted non-residential floor area by at least 200,000 zoning square feet`
line 94 in the `equitable-development-reporting.hbs`
- Fixes [AB#8718](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8718)
- Correction to [AB#8426](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8426)

8718 correct copy for tooltip

---

server/src/document/document.controller.ts

Fixes [AB#8334](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8334) 
Previously this ticket wasn't addressed properly. Sharepoint may have 100mb restrictions, but we want to stop Node from even processing files larger than 100mb and attempting to post to Sharepoint.

8334 Stop processing of large doc uploads

---

server/src/document/document.controller.ts

Fixes [AB#8915](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8915)
Recently we stripped all uploaded Artifact document names of special characters to prevent complications when downloading and removing the files. Here we do the same for package  documents.

8915 Strip package file names

---

client/app/routes/pas-form/edit.js

added class to check for project status and state codes and redirects to the PAS show page if package was submitted and marked inactive
added `client/app/routes/pas-form/edit.js` to intercept the default edit route to check for package status.
- Fixes [AB#989](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/989)

989 add check to see if PAS was submitted and inactive, then redirecting to show page if true

---

client/app/routes/pas-form/edit.js

added class to check for project status and state codes and redirects to the PAS show page if package was submitted and marked inactive
added `client/app/routes/pas-form/edit.js` to intercept the default edit route to check for package status.
- Fixes [AB#989](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/989)

Bug/989 prevent users from going back on after package submit actions 

---

server/src/packages/packages.service.ts
server/src/packages/rwcds-form/rwcds-form.service.ts

Addinal error logging in RWCDS form service
bug was caused my CMS input field that awsa too long. Attached photos have details.
- Fixes [AB#8125](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8125)

8125 additional logging in RWDCS form service to catch errors

---

client/app/components/project/milestones/milestone-group-item.js

For milestones to appear in the milestones group list, the milestone must be listed in the `projectToShow` array in the `milestone-group-item.js`.  There is probably a way to populate this array with additional ad hoc milestone without needing to add them manually but that is beyond the scope of this bug ticket.
- Fixes [AB#1497](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/1497)
####AFTER:

1497 added urban design guidance to projects to show array

---

client/config/environment.js
client/mirage/config.js
client/package.json
client/yarn.lock

Blocked by/Depends on Depends on https://github.com/NYCPlanning/labs-search-api/pull/58
(Rerun Tests  after  https://github.com/NYCPlanning/labs-search-api/pull/58 is merged)
Fixes [AB#9400](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/9400)

9400 Use geosearch v2

---

client/config/environment.js
client/mirage/config.js
client/package.json
client/yarn.lock

This PR merges a feature branch into master that switches the app to use the Geosearch v2 helper and upgrades to the most recent version of `labs-ember-search`. This is being done via a feature branch into master because `develop` and `qa` branches already have other changes that aren't ready for master.

Release 9400 search api geosearchv2 upgrade to production

---

client/app/components/packages/pas-form/project-area.hbs
client/app/components/packages/rwcds-form/proposed-project-actions.hbs
client/app/components/packages/rwcds-form/show.hbs
client/app/helpers/optionset.js
client/app/models/pas-form.js
client/app/models/rwcds-form.js
server/src/packages/pas-form/pas-form.attrs.ts
server/src/packages/rwcds-form/rwcds-form.attrs.ts

This PR removes code #1203 #1204 and #1218 related to the new questions for Green Fast Track CEQR type 2 eligibility. We have to do this so that we can release the changes in #1224 for converting to MSFT's Graph API for Sharepoint. We will revert this PR once the Green Fast Track changes are due to be released to prod.

Remove code related to new Green Fast Track CEQR Type 2 eligibility to unblock release of Sharepoint Graph API conversion

---

.github/workflows/code-quality.yml
client/config/environment.js

Make a workflow specific to code quality checks that runs on pull requests
Fix errors causing code quality checks to fail
closes #1272

Run code quality checks on pull requests

---

client/app/components/packages/projects/new.hbs
client/app/components/packages/projects/new.js
client/app/components/packages/projects/projects-new-information.hbs
client/app/models/package.js
client/app/models/project.js
client/app/router.js
client/app/routes/projects/new.js
client/app/templates/projects/new.hbs
client/app/validations/submittable-projects-new-form.js
client/tests/unit/routes/projects/new-test.js
server/src/projects/projects.controller.ts

Create new project form skeleton
Initialize the parts required for a new project form
closes #1245

Issue 1245:  Skeleton form for new project

---

server/src/contact/contact.controller.ts
server/src/contact/contact.service.ts

Add a POST endpoint to the contacts controller to access the contact creation service
closes #1247 
Updates the "get contact" endpoint to support finding all contacts, regardless of status code. This allows the finding of inactive contacts. The behavior is opt-in, to preserve behavior that relies on only seeing active records.

Support the creation of contacts

---

client/app/components/packages/projects/new.js
client/app/components/packages/projects/projects-new-information.hbs
client/app/models/project.js
client/app/routes/projects/new.js
client/app/validations/submittable-projects-new-form.js

Request the creation of a new contact if it does not exist
closes #1248
dependent on #1289 
The Ember Data model was not cooperating with the desired behavior. Ember data wants us to make requests directly to "project". However, we need to make several calls to different endpoints. Consequently, we instead use a basic object to track the fields and their validations in the form. On form submit, we divide the form data into separate Ember Data models that can make the necessary requests.
There was an open question in #1247 about whether to update existing contact details if they differ from what the user submits with the project form. This PR chooses not to update the details. If the contact already exists, then it uses the details as listed in CRM. The thought is that this feature is to …

Submit contact details

---

.github/workflows/production.yml
.github/workflows/qa.yml

Refactor qa alias to qa2
Remove master alias
closes #1267

Update branch deploy aliases
