server/Procfile

Adds a Procfile.
Addresses #32

Add basic Procfile for heroku deployment

---

server/package-lock.json
server/package.json
server/src/app.module.ts
server/src/projects/projects.controller.spec.ts
server/src/projects/projects.controller.ts
server/src/projects/projects.module.ts
server/src/projects/projects.service.spec.ts
server/src/projects/projects.service.ts
server/yarn.lock

Create projects endpoint that grabs all projects associated with the current user based on the contact id.
Contact that has more than one project to use for testing: `6B67210A-DB76-EA11-A811-001DD83095B2`
Future CRM Web API URL to use for statecode/statuscode/dcp_visibility conditions:
`dcp_projects?$filter=dcp_dcp_project_dcp_projectapplicant_Project/any(o:o/_dcp_applicant_customer_value%20eq%20%27${contactId}%27)%20and%20(dcp_visibility%20eq%20${projectVisibilityApplicantOnly}%20or%20dcp_visibility%20eq%20${projectVisibilityGeneralPublic})&$expand=dcp_dcp_project_dcp_package_project($filter=%20statecode%20eq%20${activeStatusCode}%20and%20(dcp_visibility%20eq%20${packageVisibilityApplicantOnly}%20or%20dcp_visibility%20eq%20${packageVisibilityGeneralPublic})),dcp_dcp_project_dcp_projectapp …

15: projects endpoint--queries for all projects associated w/ applicant

---

server/src/projects/projects.controller.ts

In projects.controller.ts, acquire the `contactId` from `session` rather than from the CRM_IMPOSTER_ID. 
Addresses #15

15: acquire contactId from session in projects endpoint

---

client/app/controllers/projects.js
client/app/models/project.js
client/app/routes/projects.js
client/mirage/factories/project.js
client/tests/acceptance/user-sees-projects-of-all-types-test.js
server/src/projects/projects.controller.ts

This PR enables a QP for client and honors that QP value in the backend by preferring the creeper mode value over the ID.
Includes client side acceptance test.

Enable creeper mode params

---

README.md
client/config/environment.js
client/package.json
server/src/main.ts

This commit changes some environment settings for client and server which allow us to run a local SSL server. Readme is updated.

Add setup and configuration for local development

---

client/app/components/projects/planning-project-card.hbs
client/app/components/projects/planning-project-card.js
client/app/controllers/projects.js
client/app/models/project.js
client/app/templates/projects.hbs
client/mirage/factories/project.js
client/tests/acceptance/user-sees-projects-of-all-types-test.js
client/tests/integration/components/planning-project-card-test.js
server/src/projects/projects.service.ts

73 update project list logic

---

client/app/templates/projects.hbs
client/tests/acceptance/user-sees-projects-of-all-types-test.js

Updates the text as per Azure ticket mentioned in #87

87 Update text displayed when user has no assigned projects

---

client/app/routes/index.js
client/tests/acceptance/user-can-login-test.js

Redirects user to projects page when visiting index route if already logged in
Closes #79

79: redirect user to projects page when they visit index if already logged in

---

CODEOWNERS
ISSUE_TEMPLATE.md

Demo Pull Request 

---

server/src/projects/projects.controller.ts

Transform ugly package name attr to nicer name "packages".

Serialize project packages

---

client/app/models/package.js
client/app/models/pas-form.js
client/app/serializers/application.js
client/app/serializers/package.js
client/mirage/config.js
client/mirage/models/applicant.js
client/mirage/models/bbl.js
client/mirage/models/pas-form.js
client/package.json
client/tests/unit/models/package-test.js
client/tests/unit/serializers/application-test.js
client/tests/unit/serializers/package-test.js
client/yarn.lock
server/src/authenticate.guard.spec.ts
server/src/authenticate.guard.ts
server/src/json-api-deserialize.pipe.spec.ts
server/src/json-api-deserialize.pipe.ts
server/src/packages/packages.controller.ts
server/src/packages/packages.module.ts
server/src/packages/pas-form/applicants/applicants.controller.spec.ts
server/src/packages/pas-form/applicants/applicants.controller.ts
server/src/packages/pas-form/bbls/bbls.controller.spec.ts
server/src/packages/pas-form/bbls/bbls.controller.ts
server/src/packages/pas-form/pas-form.controller.spec.ts
server/src/packages/pas-form/pas-form.controller.ts
server/src/packages/pas-form/pas-form.service.spec.ts
server/src/packages/pas-form/pas-form.service.ts
server/src/projects/projects.controller.ts

This PR addresses another part of the PAS Form system, the ability to post and patch data into the system.

PAS Form Routes, Controllers, Models, Handlers

---

client/app/components/packages/pas-form/edit.hbs
client/app/components/packages/pas-form/edit.js
client/mirage/config.js
client/tests/integration/components/pas-form-test.js

This PR will add the save button frontend logic.

Save PAS form on save button click

---

.circleci/config.yml
server/package.json
server/test/document.e2e-spec.ts
server/yarn.lock

This PR enables e2e testing in CircleCI. Adds environment variable mocking in the doc upload test.

Enable e2e backend tests; Add to CI

---

client/app/components/packages/pas-form/edit.hbs

Addresses #122 by pasting in the URLs from the wireframes.

122: provide real hyperlinks

---

client/app/templates/projects.hbs

Addresses #128, where the help message on the My Projects view was mistakenly nixed.

fix missing help message on My Projects

---

client/app/components/packages/pas-form/edit.hbs

Addresses #121. The city register question should only appear if the previous dcprestrictivedeclaration answer is yes/true.

121: make city register question conditional

---

client/app/components/action-form-input.hbs
client/app/components/action-form-input.js
client/app/components/land-use-action.hbs
client/app/components/land-use-action.js
client/app/components/packages/pas-form/edit.hbs
client/app/models/pas-form.js
client/app/styles/app.scss
client/app/styles/modules/_pasform.scss
client/mirage/config.js
client/package.json
client/tests/integration/components/action-form-input-test.js
client/tests/integration/components/land-use-action-test.js
client/yarn.lock

- This PR creates a LandUseAction component where a user can select an action from the dropdown menu and then answer additional questions about that added action. 
- The PR uses a child component action-input-form to standardize form inputs since there are additional questions required by many actions (some of which are similar to other actions).
**Questions:**
- How do other engineers prefer to store lookups? Outside of the file where it's used or inside of it? I left the lookup inside the file for easy access, but am open to suggestions. 
- A lot of lookups and naming going on here! Will take any suggestions on names
**TODO:**
- Working on design update final polishing
- Double check that attributes included in the lookup are correct based on CRM fields (double checking and polishing …

22 land use action component

---

client/app/components/packages/applicant-fieldset.hbs
client/app/models/applicant.js
client/app/models/pas-form.js
client/mirage/factories/applicant.js
server/src/packages/packages.controller.ts

Updates fields to correct names; provides all PAS form fields

Fix attr fields, align with CRM

---

client/app/components/projects/applicant-project-card.hbs
client/app/models/package.js
client/app/models/project.js
server/src/packages/packages.controller.ts
server/src/projects/projects.controller.ts

Not sure if this is the right field but this swap for versionnumber  for dcp_packageversion

Swap versionnumber for dcp_packageversion

---

client/app/components/packages/pas-form/edit.hbs
client/app/styles/app.scss

This PR fixes the PAS Form page anchors so that the sidebar menu works, offsetting the scroll position to account for the sticky header.

Fix Form Anchors

---

client/app/components/packages/pas-form/edit.hbs
client/app/components/packages/pas-form/edit.js
client/app/templates/packages/show.hbs
client/tests/integration/components/pas-form-test.js

Adds submit button. Cleans up show template

Submit form, transition to show

---

client/app/components/packages/pas-form/edit.hbs
client/app/components/packages/pas-form/show.hbs
client/app/components/project-geography.hbs

Addresses #126 by providing a prompt that explains what type of applicant team members to add.
Addresses #125 by making capitalization consistent.

125, 126: improve questions

---

client/app/components/breadcrumbs.hbs

This PR fixes the broken link in hardcoded breadcrumbs. 
Addresses #137.

Fix breadcrumb link

---

client/app/components/packages/pas-form/edit.hbs
client/app/components/packages/pas-form/edit.js
client/app/controllers/packages/edit.js
client/app/templates/packages/edit.hbs
client/tests/acceptance/user-can-click-package-edit-test.js
client/tests/integration/components/pas-form-test.js
client/tests/unit/controllers/packages/edit-test.js

Use a callback function, events, for handling save/submit triggers.

Extract model methods from pas-form class

---

client/app/models/package.js

Refactor state code so it’s pulled from a dictionary.
Addresses #216

Set package to submitted on submit

---

client/app/styles/app.scss

prevent form elements having z-index > site-header

---

client/app/components/land-use-action.hbs
client/app/components/packages/applicant-team-editor.hbs
client/app/components/project-geography.hbs
client/app/styles/app.scss
client/app/styles/modules/_geosearch.scss

This PR improves the CSS for the BBL adder (and makes all the fieldset adders match aesthetics).

improve the BBL/GeoSearch dropdown styles

---

client/app/styles/modules/_pasform.scss

The tiny PR does what the title says.

Prevents textareas from being resized horizontally

---

client/app/components/packages/pas-form/edit.hbs
client/app/components/packages/pas-form/edit.js

Plugs in all the behavior of generic saveable form into the pas form edit component.

Use SaveableForm in pas-edit

---

client/app/controllers/projects.js
client/tests/acceptance/user-sees-projects-of-all-types-test.js

Sort alphabetically using localeCompare

---

client/app/components/land-use-action.js

Move initialization of selectedActions into constructor so it is

Refactor memory use in Land Use Action component

---

client/app/components/packages/pas-form/show.hbs
client/app/styles/app.scss

This PR fixes up the PAS show template.

Improve PAS form show template

---

client/app/components/breadcrumbs.hbs
client/app/components/breadcrumbs.js

Displays route name in breadcrumbs

Display route localName

---

client/app/router.js
client/package.json
client/yarn.lock

This adds EmberRouterScroll into the Router, makes it global.
Every route transition means a scroll to the top of the page.

Install EmberRouterScroll, make global

---

client/app/components/land-use-action.hbs

Re-add styling changes that got lost in a past merge conflict for `landUseAction` component.

Update minor styling changes on land-use-action component

---

client/app/components/packages/pas-form/show.hbs

This PR addresses #258 (changing the conditions for when sub-questions show) and improves the design of the PAS show template.

improve logic and layout of PAS show

---

client/app/styles/app.scss
client/ember-cli-build.js

The PR optimizes our Sass compiling, which was previously taking upwards of 25 seconds. I've got it consistently under 9 with this change. This is still quite a long build, but way better.

optimize Sass compile

---

client/app/components/packages/applicant-fieldset.hbs
client/app/components/packages/applicant-fieldset.js
client/app/components/project-geography.js
client/app/components/projects/planning-project-card.js
client/app/controllers/projects.js
client/app/helpers/helpers.md
client/app/helpers/optionset.js
client/app/models/applicant.js
client/app/models/bbl.js
client/app/models/package.js
client/mirage/factories/package.js
client/tests/integration/helpers/optionset-test.js

This PR introduces a helper for a standardized way of working with optionsets and their codes and values in templates.
Addresses #255

255 optionset helper

---

client/app/components/packages/pas-form/edit.hbs

Addresses #357 . Improves instructions for attachments applicants need to include with the PAS form.

357: improve attachment instructions

---

client/app/components/packages/pas-form/edit.hbs
client/app/components/text-area.hbs
client/app/components/text-area.js
client/app/components/text-input.hbs
client/app/components/text-input.js
client/tests/acceptance/pas-form-validation-messages-display-test.js

Text Inputs and Textareas are consistently rendered along
with CharacterCounter and ValidationMessage components.
Hence, we componentize text Inputs and Textareas each along
with CharacterCounter and ValidationMessage.

322 Componentize text Inputs and Textareas

---

client/app/components/packages/pas-form/edit.hbs
client/app/components/saveable-form.hbs
client/app/components/saveable-form.js
client/app/components/saveable-form/section.hbs
client/app/components/saveable-form/section.js
client/tests/integration/components/saveable-form/section-test.js

Depends on #418 
Yields out sections which register automatically to generate the "sticky sidebar"/scrollspy

Yield sections

---

client/app/components/packages/pas-form/project-area.hbs
client/app/components/ui/external-link.hbs
client/app/components/ui/fieldset-legend.hbs
client/app/components/ui/fieldset.hbs
client/tests/integration/components/ui/external-link-test.js
client/tests/integration/components/ui/fieldset-legend-test.js
client/tests/integration/components/ui/fieldset-test.js

This PR adds a new components for fieldsets, legends, and external links.

add fieldset and external link components

---

client/app/components/land-use-action.hbs
client/app/components/packages/applicant-fieldset.hbs
client/app/components/packages/attachments.hbs
client/app/components/packages/pas-form/project-area.hbs
client/app/components/packages/pas-form/proposed-development-site.hbs
client/app/components/project-geography.hbs
client/app/components/ui/fieldset-legend.hbs

This PR standardizes the use of the `<UI::Fieldset />` component everywhere.

Improve all the Fieldsets

---

client/app/components/packages/pas-form/attached-documents.hbs
client/app/components/packages/pas-form/project-area.hbs
client/app/components/packages/pas-form/project-geography.hbs
client/app/components/packages/pas-form/proposed-development-site.hbs
client/app/components/project-geography.hbs
client/app/components/ui/external-link.hbs

This PR implements the `<Ui::ExternalLink />` component throughout the content. 
It also adds splatributes to the component (e.g. so it can be passed a `.nowrap` class to prevent the icon wrapping to the next line in certain cases).

ExternalLink 

---

client/app/components/packages/pas-form/proposed-development-site.hbs

458: add zola as resource for inclusionary housing name question

---

client/app/components/packages/rwcds-form/proposed-project-actions-editor.hbs
client/app/components/packages/rwcds-form/proposed-project-actions-editor.js
client/app/components/packages/rwcds-form/proposed-project-actions.hbs
client/app/components/packages/rwcds-form/with-action-no-action.hbs
client/app/models/affected-zoning-resolution.js
client/app/validations/saveable-affected-zoning-resolution-form.js
client/tests/acceptance/user-can-click-rwcds-form-edit-test.js

- Add `dcpZrsectiontitle` as new field on `affected-zoning-resolution` model
- Add new input question on rwcds form for `dcpZrsectiontitle`
- update styling on `proposed-actions-editor` component and `with-action-no-action` component
Addresses #223

223: add zrsectiontitle question to proposed actions component

---

client/app/components/packages/applicant-fieldset.hbs
client/app/validations/saveable-applicant-form.js
client/mirage/factories/applicant.js
client/tests/acceptance/error-message-appears-when-save-fails-test.js

Use changeset validator to regulate format for phone and email fields.
Use HTML Number field to force number entry for zipcode.
Addresses #313. Addresses #298.

313 Enforce data types for applicant fields

---

client/app/components/packages/pas-form/applicant-team.hbs
client/app/components/packages/pas-form/attached-documents.hbs
client/app/components/packages/pas-form/edit.hbs
client/app/components/packages/pas-form/pas-form-error.hbs
client/app/components/packages/pas-form/project-area.hbs
client/app/components/packages/pas-form/project-description.hbs
client/app/components/packages/pas-form/project-geography.hbs
client/app/components/packages/pas-form/proposed-development-site.hbs
client/app/components/packages/pas-form/proposed-land-use-actions.hbs
client/app/components/packages/pas-form/show.hbs
client/app/components/packages/project-geography.hbs

This PR is simply text changes that improve the PAS edit view, using capitalization consistently.

Improve PAS instructions

---

client/app/components/packages/applicant-fieldset.hbs
client/app/validations/saveable-applicant-form.js
client/tests/acceptance/pas-form-validation-messages-display-test.js

Also use HTML to prevent user from entering letters for
dcpPhone

313 Add tests for applicant validation

---

client/app/components/packages/rwcds-form/with-action-no-action.hbs
client/tests/acceptance/user-can-click-rwcds-form-edit-test.js

Fix with-action-no-action component conditional display logic 
Addresses #482 
Remade PR due to conflicts -- used to be in PR #491

482: fix with-action-no-action conditional display logic

---

client/app/components/packages/pas-form/project-area.hbs
client/app/components/packages/pas-form/show.hbs

Per request from Waterfront and Open Space team:
- Adds an external link resource to the stormwater question
- Changes "storm water" to "stormwater"

357: improve stormwater q instructions

---

client/app/components/packages/pas-form/applicant-team.hbs
client/app/components/packages/pas-form/edit.js
client/app/components/saveable-form/index.hbs
client/app/utils/ember-changeset.js
client/app/validations/submittable-pas-form.js
client/tests/acceptance/pas-form-validation-messages-display-test.js
client/tests/acceptance/user-can-click-pas-form-edit-test.js
server/src/packages/pas-form/pas-form.service.ts

Draft solution for #510, uses changeset validations.
This does not show an error message yet, but it does validate.
@godfreyyeung , this mostly follows https://davidtang.io/2018/07/28/tracking-has-many-relationship-changes-with-ember-changeset.html

510: Validate has many length

---

server/src/auth/auth.service.ts
server/src/contact/contact.service.ts

Quick fix to:
1. Make sign-in with e-mail case insensitive
2. Provide the e-mail used to login.

Query by e-mail, case insensitive; Improve error msg

---

server/src/packages/packages.attrs.ts
server/src/projects/projects.attrs.ts
server/src/projects/projects.controller.ts
server/src/projects/projects.service.ts

Addresses #468 
Sets up an endpoint to GET a project of specific ID.
It will sideload packages and applicant team members.
It only returns the project if the signed in contact
is part of the project's applicant team.

468 Backend projects/id endpoint

---

client/app/components/packages/rwcds-form/show.hbs

Cribbed from PAS show template
Addresses #531

Show list of attachments

---

client/app/components/packages/rwcds-form/proposed-project-actions.hbs

545: fix ceqr technical manual link on proposed actions section on rwcds form

---

server/README.md

Prepping for a wider project documentation effort

Reset server readme to make it our own

---

client/app/adapters/application.js
client/app/authenticators/zap-api-authenticator.js
client/app/components/auth/do-logout.hbs
client/app/components/auth/do-logout.js
client/app/components/packages/pas-form/pas-form-error.hbs
client/app/components/packages/rwcds-form/rwcds-form-error.hbs
client/app/controllers/login-error.js
client/app/routes/login.js
client/app/templates/login-error.hbs
client/app/templates/logout.hbs
client/tests/acceptance/user-can-login-test.js
client/tests/unit/authenticators/zap-api-authenticator-test.js
server/package.json
server/src/app.controller.ts
server/src/app.module.ts
server/src/auth.middleware.ts
server/src/auth/auth.module.ts
server/src/auth/auth.service.ts
server/test/document.e2e-spec.ts
server/test/helpers/extract-jwt.ts

This PR addresses NYCPlanning/labs-zap-search#1211 (wrong repo?) by using token-based auth, eliminating the need for cross-site cookies (and the sameSite=none attribute)

Kill all cookies

---

server/src/packages/packages.controller.ts
server/src/projects/projects.controller.ts

Wrap the transform functions within the Project and
Package interceptors in try-catch statements as well,
since they may sometimes yield errors (e.g. when
trying to transform undefined objects).

526 Wrap Project+Package interceptor transform in try-catch

---

client/app/models/package.js
client/app/services/file-manager.js

Include the authorization header with document
creation and deletion requests

589 Incl. Auth header w document creation & delete

---

client/app/components/packages/rwcds-form/show.hbs

582 Display list of actions on RWCDS show page

---

client/app/components/packages/rwcds-form/show.hbs

583 conditionally display dcpRwcdsexplanation value on RWCDS show page

---

server/src/projects/projects.service.ts

Add package filters to GET for single project based on package `dcp_visibility` and `statuscode`
Addresses #577

577: filter packges on project page for visibility and statuscode

---

client/app/components/packages/pas-form/project-area.hbs
client/app/components/packages/pas-form/proposed-development-site.hbs
client/app/components/packages/rwcds-form/with-action-no-action.hbs

This helps futureproof the forms in case CRM optionset values
are modified.

Use YES_NO optionsets in forms

---

client/app/components/packages/rwcds-form/show.hbs

Fixes [AB#12128](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12128). 
We were looking for the answer on the PAS package instead of the RWCDS. Oops! 🤦‍♂️

🐞 fix dcpIsplannigondevelopingaffordablehousing show

---

client/app/components/packages/rwcds-form/show.hbs

Fixes [AB#12124](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12124).

🐞 fix typos

---

server/EXCEPTIONS.md
server/src/app.controller.ts
server/src/auth/auth.service.ts
server/src/contact/contact.service.ts

Will properly display error for the /login route, like so:
Also document the need for logging out errors

Standardize exception handling for login

---

client/app/components/project/project-editor-list-item.hbs
client/app/models/project-applicant.js
client/app/models/project.js
client/app/routes/project.js
client/app/templates/project.hbs
client/mirage/models/project-applicant.js
client/mirage/models/project.js
client/tests/integration/components/project/project-editor-list-item-test.js
client/tests/unit/models/project-applicant-test.js
server/src/projects/project-applicants/project-applicants.attrs.ts
server/src/projects/projects.controller.ts
server/src/projects/projects.service.ts

List of project editors displays on individual project page.
Fixes [AB#12157](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12157)

12157: add project editor list to project page

---

client/app/components/auth/do-logout.hbs
client/app/components/packages/rwcds-form/show.hbs
client/tests/integration/components/auth/do-logout-test.js

This PR…
- Add page anchors to the RWCDS show template sections
- Reformats the "Proposed Actions" section of the RWCDS show template
Fixes [AB#12161](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12161).

improve layout of RWCDS show

---

client/app/components/auth/sign-in-button.hbs
client/app/components/auth/sign-in.hbs
client/app/components/index-header.hbs
client/app/templates/auth.hbs
client/app/templates/auth/login.hbs
client/app/templates/auth/register.hbs
client/app/templates/auth/validate.hbs
client/app/templates/index.hbs

💅 update auth templates/layouts

---

client/app/validations/saveable-landuse-form.js
client/app/validations/saveable-related-action.js
client/app/validations/submittable-landuse-form.js
client/app/validations/submittable-related-actions.js

Validations for:
- saveable landuseForm
- submittable landuseForm
- saveable relatedActions
- submittable relatedActions

12240: add validations for landuse form and associated models

---

client/app/components/packages/landuse-form/edit.hbs
client/app/components/packages/landuse-form/edit.js
client/app/models/landuse-form.js

Closes [AB#12240](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12240)

12240: incorporate saveableForm into landuse-form

---

client/app/components/auth/sign-in.hbs

This PR runs `startLogin()` when the user presses enter in the email text input.

Allow pressing enter to trigger auth

---

client/app/models/package.js
server/src/json-api-deserialize.pipe.ts
server/src/packages/landuse-form/landuse-form.controller.ts
server/src/packages/pas-form/applicants/applicants.controller.ts

Include various overlooked steps to patch land use form
and land use applicants
Fixes [AB#12252](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12252)

12252 Fix patching Land Use form and LU applicants

---

client/app/templates/auth/login.hbs
client/app/templates/auth/register.hbs
client/app/templates/auth/validate.hbs

This PR improves the login routes by… 
- Nixing the hardcoded email address
- Showing the user-entered email address

🤦‍♂️ Show user-entered email address (not email.example.org)

---

client/app/components/auth/sign-in.hbs
client/app/components/auth/sign-in.js

This PR…
- Use an action on a form element to `startLogin()`
- Deletes the actions on the input and button
- Changes the button to a submit (this way a button click or an input enter will trigger the action)

💅 Improve sign in email detector

---

server/src/contact/contact.service.ts
server/src/projects/project-applicants/project-applicant.controller.ts

Refactor the project-applicant controller to use the contact service’s create method

Set dcp_contactstatus to active

---

client/app/components/auth/do-logout.js
client/app/components/project/project-editor-list-item.hbs
client/app/helpers/format-phone.js
client/app/models/contact.js
client/app/templates/project.hbs
client/mirage/config.js
client/tests/integration/helpers/format-phone-test.js
server/src/contact/contacts.attrs.ts

Addresses [AB#12453](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12453)

Display applicant team phone number

---

client/app/templates/project.hbs

Addresses [AB#12454](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12454)

Make toggle action close modal instead of save

---

server/src/projects/projects.service.ts

Addresses [AB#12457](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12457)

Order team members ascending

---

client/tests/acceptance/user-can-click-landuse-form-edit-test.js

Closes [AB#12367](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12367)

12367: create acceptance test for tax lot selector on landuse-form

---

client/config/environment.js
netlify.toml

We want to hide the contact management features in production, but show them in QA.

Parameterize feature flags through netlify vars

---

client/app/routes/projects.js
client/tests/acceptance/user-can-login-test.js

Resolves [AB#12458](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12458)
Redirects the user when the server comes back with a 403

When unauthorized, invalidate session and redirect

---

client/app/components/packages/deis/edit.hbs
client/app/components/packages/deis/edit.js

Fixes [AB#13058](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13058) 
Setup save for DEIS
Same as draft EAS

13058 setup save button for deis

---

client/app/components/project/package-section.hbs
client/app/components/project/package-section.js
client/app/components/project/package-section/invoice-info.hbs
client/app/models/invoice.js
client/app/models/package.js
client/app/templates/project.hbs
client/app/utils/ember-changeset.js
client/ember-cli-build.js
client/tests/integration/components/project/package-section-test.js
client/tests/integration/components/project/package-section/invoice-info-test.js
client/tests/unit/models/invoice-test.js
client/tests/unit/models/landuse-action-test.js
client/tests/unit/models/landuse-form-test.js
client/tests/unit/models/project-applicant-test.js
client/tests/unit/models/related-action-test.js
client/tests/unit/models/team-member-test.js
client/tests/unit/routes/auth/login-test.js
client/tests/unit/routes/auth/register-test.js
client/tests/unit/routes/auth/sync-test.js
client/tests/unit/routes/auth/validate-test.js
client/tests/unit/routes/invoice-test.js
client/tests/unit/routes/project-test.js
server/src/app.module.ts
server/src/citypay/citypay.service.ts
server/src/invoices/invoices.attrs.ts
server/src/invoices/invoices.controller.ts
server/src/invoices/invoices.module.ts
server/src/invoices/invoices.service.ts
server/src/projects/projects.controller.ts
server/src/projects/projects.service.ts

Adds the UI for fetching the payment link for invoices. Lists invoices and links to their show view.
Payment
No way to pay — this adds the UI to interact with the payment endpoint.
Just some components. The component hits the altready-built citypay service in the backend, which generates a citypay link. This link is sent to the user client.
Want to get some eyes on this, will fill out test coverage tomorrow.
Branches off some of @dhochbaum-dcp work.

12720 list invoices project view

---

client/app/components/packages/feis/edit.hbs
client/app/components/packages/feis/edit.js

13054 Setup save button for FEIS
Fix AB [13054](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/13054)
Same as Draft EAS Save Button

13054 Setup save button for FEIS

---

client/app/components/packages/draft-eas/edit.hbs
client/app/components/packages/technical-memo/edit.hbs

Add Package Notes to Draft EAS and Technical Memo package Edit components. 
Tests will be added as a part of [AB#13209](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13209) 
Fixes [AB#13031](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13031)
Fixes [AB#13068](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13068)

13031 13068 Add Package Notes to Draft EAS and Technical Memo packages

---

client/app/components/contact-manager.hbs
client/app/components/contact-manager.js
client/app/controllers/project.js
client/app/models/project-applicant.js
client/app/routes/project.js
client/app/templates/project.hbs
client/tests/integration/components/contact-manager-test.js
server/src/contact/contact.module.ts
server/src/contact/nycid/nycid.service.ts
server/src/projects/projects.controller.ts
server/src/projects/projects.module.ts
server/src/projects/projects.service.ts

Show "send inv" button only if they are flagged as not registered
Closes [AB#12455](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12455)
Queries NYC.ID for every team member, checking if they're registered in the system. yes, does a separate request each time. Includes some logic to prevent the request if an NYC.iD GUID has already been recorded.

12455 send inv button bug

---

client/app/components/packages/feis/edit.hbs

13050 Display Package Notes in FEIS
Close [AB#13050](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/13050)
Same as Display Package Notes in Draft EAS

13050 Display Package Notes in FEIS

---

client/app/templates/project-loading.hbs
server/src/packages/landuse-form/landuse-form.service.ts

Filter out inactive subject sites
[AB#12878](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12878)
Adds a filter condition to the CRM API

Filter for active subject sites

---

client/app/components/packages/deis/attached-documents.hbs
client/app/components/packages/feis/attached-documents.hbs
client/app/components/packages/feis/edit.hbs

13048 Add Attachments section to FEIS
Fix AB [13048](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/13048)
Same as Draft EAS Attachment

13048 Add Attachments section to FEIS

---

client/app/components/packages/landuse-form/public-facilities.hbs

Fixes [AB#12869](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12869)
Moved question, updated if statement to make question display conditionally.

Updated logic  for when the questions show

---

client/app/components/packages/deis/attached-documents.hbs
client/app/components/packages/deis/edit.hbs
client/app/components/packages/feis/attached-documents.hbs
client/app/components/packages/feis/edit.hbs
client/mirage/factories/package.js
client/tests/acceptance/user-can-edit-deis-test.js
client/tests/acceptance/user-can-edit-feis-test.js

13210 Write tests for Draft and Final EIS package
Close [AB#13210](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/13210)
Same as #822

13210 Write tests for Draft and Final EIS package

---

client/app/components/packages/draft-eas/edit.hbs
client/app/components/packages/filed-eas/attached-documents.hbs
client/app/components/packages/filed-eas/edit.hbs
client/mirage/factories/package.js
client/tests/acceptance/user-can-edit-filed-eas-test.js

Same as PR #822 , but for Filed EAS 
Fixes [AB#13209](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13209)

13209 Filed EAS test steup

---

client/app/components/packages/deis/deis-error.hbs
client/app/components/packages/deis/edit.hbs
client/app/components/packages/deis/edit.js
client/app/components/packages/deis/show.hbs
client/app/components/packages/feis/edit.hbs
client/app/components/packages/feis/edit.js
client/app/components/packages/feis/feis-error.hbs
client/app/components/packages/feis/show.hbs
client/tests/acceptance/user-can-edit-deis-test.js
client/tests/acceptance/user-can-edit-feis-test.js

13057 Setup submission for DEIS
13060 Setup show page for Draft EIS
13072 Set up submission for FEIS
13061 Setup show page for Final EIS
Close [AB#13057](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/13057)
Close [AB#13060](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/13060)
Close [AB#13072](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/13072)
Close [AB#13061](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/13061)
Same as #831

13057-13060-13072-13061 Submission and Show Page for feis and deis

---

client/app/components/packages/scope-of-work-draft/edit.hbs
client/app/components/packages/scope-of-work-draft/edit.js
client/app/components/packages/scope-of-work-draft/show.hbs

13254 Update Draft SOW to DSOW for anything public
Close [AB#13254](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/13254)
Copy and Paste

Update Draft SOW to DSOW for anything public

---

client/app/components/packages/landuse-form/proposed-action-editor.hbs
client/app/components/packages/landuse-form/show.hbs

13313 address On the submitted LU form, certain fields are not displayed 
Fixes AB#[13313](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/13313)
Correct Typo for affected fields and use optionset for yes/no questions

13313 address On the submitted LU form, certain fields are not displayed 

---

client/app/components/packages/landuse-form/proposed-actions.hbs

**Summary**
Fix incorrect question text on Proposed Actions section on landuse-form
Fixes [AB#12782](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12782)

12782: fix incorrect question text on Proposed Actions section on landuse-form

---

server/src/projects/projects.service.ts

Fixes [AB#13280](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13280)
Filters out invoices by status/state codes

Only include active and approved invoices

---

client/app/components/packages/landuse-form/show.hbs
client/app/components/project/package-section.hbs
client/app/components/project/package-section.js
client/app/components/project/package-section/invoice-info.hbs
client/app/models/invoice.js
client/ember-cli-build.js
client/tests/integration/components/project/package-section/invoice-info-test.js
server/src/invoices/invoices.attrs.ts
server/src/invoices/invoices.service.ts
server/src/projects/projects.service.ts

Merging the Invoice bug fixes into the QA Environment 

---

server/src/projects/projects.controller.ts
server/src/projects/projects.service.ts

Fixes [AB#12414](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/12414)
Undid some of the changes made in this previous commit: https://github.com/NYCPlanning/labs-applicant-portal/commit/301616b7162efc69f475461f80b3fc753df27e67

12414 Projects now appear under "Projects Awaiting Submission"

---

client/app/components/packages/landuse-form/proposed-actions.hbs

Fixes [AB#13378](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13378)

Updated help text on DLU form.

---

client/app/components/packages/landuse-form/housing-plans.hbs
client/app/components/packages/landuse-form/show.hbs
client/app/helpers/optionset.js
client/app/models/landuse-form.js

Fixes [AB#13320](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13320)
Added the two missing questions to the housing plans section of the form.

13320 - Added two questions to HA & HD applications

---

client/app/components/packages/landuse-form/primary-contact.hbs

13847 Updated the description of the primary contact

---

client/app/templates/project.hbs

13521 Add language to project page
Fixes [AB#13521](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/13521)
Copy and paste text

13521 Add language to project page

---

client/app/templates/project.hbs

13523 Correct typo
Fixes [AB#13523](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/13523)
Copy and Paste

13523 Correct typo

---

client/app/components/project/milestones/milestone-group-item.hbs
client/app/components/project/milestones/milestone-group-item.js
client/app/components/project/milestones/milestone-group.hbs
client/app/components/project/milestones/milestone-group.js

13524 Display milestones with specific criteria on the project
[Fixes AB#13524](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/13524)
Only show these projects whose dcpMilestoneValue is included in the projectsToShow provided. 
Only show these groups whose status is included in the groupsToShow provided.

13524 Display milestones with specific criteria on the project

---

client/app/templates/project.hbs

Fixes [AB#13526](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13526)
Updates to the status section.

13526 Included in-progress milestones as a list of tags

---

client/app/components/packages/ceqr-invoice-questionnaire.hbs
client/app/components/packages/ceqr-invoice-questionnaire.js
client/app/templates/project.hbs

Merge develop into qa

---

client/app/components/index-header.hbs

Fixes [AB#13565](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/13565)

Add holiday message to login page

---

PULL_REQUEST_TEMPLATE.md
client/app/routes/auth/sync.js
client/config/environment.js
client/mirage/config.js

For retesting bug 
https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/858

Merging the QA environment with Develop 

---

client/app/index.html
client/mirage/config.js

Fixes [AB#991](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/991)

991 Install helpscout

---

client/app/components/packages/landuse-form/proposed-public-facilities-action-list.js
client/app/components/packages/landuse-form/public-facilities.hbs

Address Bug [AB#1203](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/1203).

Update site selection language.

---

server/src/document/document.service.ts
server/src/sharepoint/sharepoint.service.ts

A workaround for existing sharepoint folders causing "Record already present in db" error ! 💫 
Usually, during "business as usual", when a package revision is created then the CRM scripts will generate a Sharepoint folder (and carry over files from previous revisions into it) for that package, and link the CRM package record to that Sharepoint folder. I believe there is perhaps a bug in CRM scripts that causes that linkage step to intermittently fail. I am not sure why that linkage part is failing.
Since a problematic package is not linked to a Sharepoint folder, upon document upload the Applicant Portal API will attempt to create a folder and link the CRM package record to it. However, because CRM scripts already created a Sharepoint folder, we are getting the error "Record already …

Archive existing package folders in sharepoint that block upload

---

server/src/main.ts

Fixes [AB#2048](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2048)

2048 Only allow localhost origins in development

---

client/app/components/packages/landuse-form/attached-documents.hbs

Clicking the link now works.
- Fixes [AB#1691](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/1691)
HERF

Fixed broken link

---

client/app/components/project/package-section.hbs

Fixes [AB#2866](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2866)

2866 Hide Mistake packages

---

client/app/components/packages/attachments.js

Fixes [AB#1690](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/1690)

1690 Remove deselected file from package documents array

---

client/app/components/auth/sign-in.hbs
client/app/components/auth/sign-in.js

- Fixes [AB#3625](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3625)

Add warning about upcoming maintenance

---

.gitignore
README.md
client/.gitignore
server/.gitignore

I added more items to the `.gitignore` files and corrected the heading in the README`

updates gitignore files and README

---

client/app/components/packages/rwcds-form/with-action-no-action.hbs

Update blurb with additional copy below "Description of No-Action Scenario” question under No-Action Scenario section of form
- Fixes [AB#8313](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8313)
- Related [AB#2235](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2235)

8313 Update blurb with addl copy below "Description of No-Action Scenario” question

---

client/app/components/packages/rwcds-form/with-action-no-action.hbs

updated copy to make guidance clearer to applicants
- Fixes [AB#8311](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8311)
- Related [AB#2241](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2241)

8311 update copy of second bullet in the addl guidance in the Description of No-Action scenario

---

client/app/components/packages/rwcds-form/with-action-no-action.hbs

Under the No-Action Scenario section of the RWCDS form on the Application Portal, updated the blurb under the How did you determine this No-Action Scenario? question.
- Fixes [AB#8309](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8309)
- Related [AB#2276](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2276)

8309 add addl copy to "How did you determine this No-Action scenario" guidance

---

client/app/components/packages/rwcds-form/with-action-no-action.hbs

Applicant RWCDS Form - Update blurb under "How did you determine this With-Action Scenario?" question under With-Action Scenario section of form 
- Fixes [AB#8302](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8302)
- Related [AB#2246](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2246)

8305 Update blurb under 'How did you determine this With-Action Scenario' with addl copy

---

server/src/projects/projects.controller.ts

Fixes [AB#8360](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8360)

8360 Fix project PATCH response payload

---

client/app/components/packages/equitable-development-reporting.hbs
client/app/helpers/optionset.js

Fixes [AB#8402](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8402)

8402 Display Auto Response on  PAS and LU

---

client/app/components/packages/equitable-development-reporting.hbs
client/app/components/packages/landuse-form/edit.hbs
client/app/components/packages/landuse-form/show.hbs
client/app/components/packages/pas-form/edit.hbs
client/app/models/project.js
server/src/projects/projects.attrs.ts

Fixes [AB#8441](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8441)

8441 Add extra q to LU equity  report section

---

client/app/components/packages/equitable-development-reporting.hbs
client/app/components/packages/landuse-form/edit.hbs
client/app/components/packages/pas-form/edit.hbs

Fixes [AB#8477](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8477)

8477 Display Not Subject auto response on equity report section

---

client/app/components/packages/equitable-development-reporting.hbs

updated copy line 15 in `equitable-development-reporting.hbs` : The actions(s) from "The action(s) I am applying for are ULURP actions with an acquisition or disposition of land for:

8516 removed copy The actions(s) in PAS Racial Equity Section

---

client/app/components/packages/equitable-development-reporting.hbs

additional guidance under question “New, enlarged, or converted residential building of  50,000 zoning square feet or more.”
- Fixes [AB#8419](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8419)
-

8419 additional guidance under question new, enlarged, or converted residential building 

---

client/app/components/packages/equitable-development-reporting.hbs

Added tooltip as per Figma designs
- Fixes [AB#8572](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8572)
- Related [AB#8429](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8429)
- Parent [AB#8374](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8374)

8572 added tool tip omitted in ado #8429

---

client/app/components/packages/artifact-attachments.hbs
client/app/components/packages/equitable-development-reporting.hbs
client/app/components/packages/landuse-form/artifact-documents.hbs
client/app/components/packages/landuse-form/edit.hbs

Fixes [AB#8612](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8612)

8612 style ånd copy for  artifact attachments

---

client/app/models/package.js
client/app/models/project.js

Fixes [AB#8610](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8610) [AB#8620](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8620)

8619 8620 Ensure artifact documents reload after save

---

client/app/components/packages/attachments.hbs
client/app/components/packages/deis/attached-documents.hbs
client/app/components/packages/feis/attached-documents.hbs

Reverts NYCPlanning/labs-applicant-portal#1070

Revert "8334 Limit file uploads to 100mb. "

---

client/app/models/package.js
client/app/models/pas-form.js
server/src/packages/pas-form/pas-form.attrs.ts

Fixes [AB#8384](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8384) 
Fixes [AB#8704](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8704)

8384 Set dcpApplicability on PAS form

---

client/app/models/landuse-form.js
client/app/models/package.js
server/src/packages/landuse-form/landuse-form.attrs.ts

Fixes [AB#8705](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8705)

8705 Set dcpApplicability on LU form

---

client/app/components/packages/equitable-development-reporting.hbs
client/app/components/project/package-list-item.hbs
client/app/models/package.js

According to Liz RER applies to Post CERT LU as well

Use isLUPackage computed

---

server/src/document/document.controller.ts

Fixes [AB#8684](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8684)

8684 Remove special characters from file name on upload

---

server/src/artifacts/artifacts.service.ts

Fixes [AB#8725](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8725)

8725 Set new rer visibilty to Applicant Only

---

client/app/components/auth/sign-in.hbs
client/app/components/auth/sign-in.js
client/app/styles/app.scss
netlify.toml

Cherry picked maintenance banner implementation
- Fixes [AB#8699](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/8699)

8699 cherrypicked-enabled maintenance flags-commit base:master

---

client/app/routes/pas-form/edit.js
server/src/document/document.controller.ts

merging develop to QA for testing

Merge Develop into QA for testing

---

client/app/routes/pas-form/edit.js

This is only a PR to add logging to look into the original bug to confirm whether or not going back to PAS package bug has been fixed. This will not be merged into develop, only deleted after testing.

adding logging to test on QA site

---

client/app/routes/pas-form/edit.js
server/src/packages/packages.service.ts
server/src/packages/rwcds-form/rwcds-form.service.ts

merging develop to QA

---

client/app/components/packages/pas-form/project-area.hbs
client/app/helpers/optionset.js
client/app/models/pas-form.js
server/src/packages/pas-form/pas-form.attrs.ts

Closes [AB#16048](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/16048).

Add Type II eligibility question to PAS form

---

client/app/components/packages/rwcds-form/proposed-project-actions.hbs
client/app/components/packages/rwcds-form/show.hbs
client/app/helpers/optionset.js
client/app/models/rwcds-form.js
package-lock.json
server/package-lock.json
server/src/packages/rwcds-form/rwcds-form.attrs.ts
server/yarn.lock

Closes [AB#16049](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/16049).

Add Type II eligibility question to RWCDS form

---

client/app/components/packages/pas-form/project-area.hbs
client/app/components/packages/rwcds-form/proposed-project-actions.hbs
client/app/components/packages/rwcds-form/show.hbs
client/app/helpers/optionset.js
client/app/models/pas-form.js
client/app/models/rwcds-form.js
server/src/packages/pas-form/pas-form.attrs.ts
server/src/packages/rwcds-form/rwcds-form.attrs.ts

Reverts NYCPlanning/labs-applicant-portal#1226

Revert "Remove code related to new Green Fast Track CEQR Type 2 eligibility to unblock release of Sharepoint Graph API conversion"

---

client/app/components/packages/pas-form/project-area.hbs
client/app/components/packages/rwcds-form/proposed-project-actions.hbs
client/app/components/packages/rwcds-form/show.hbs
client/app/helpers/optionset.js
client/app/models/pas-form.js
client/app/models/rwcds-form.js
server/src/packages/pas-form/pas-form.attrs.ts
server/src/packages/rwcds-form/rwcds-form.attrs.ts

Reverts NYCPlanning/labs-applicant-portal#1227

Revert "Merge hiding CEQR Type 2 questions to QA"

---

client/app/components/packages/pas-form/show.hbs

Adds answer to Type II eligibility question to the show.hbs file for the PAS form.

Add Type II eligibility answer to PAS form

---

README.md
client/app/components/packages/pas-form/project-area.hbs
client/app/components/packages/pas-form/show.hbs
client/app/components/packages/rwcds-form/proposed-project-actions.hbs
client/app/components/packages/rwcds-form/show.hbs

Updated links in PAS and RWCDS forms updated readme
- Closes #1236

1236 Update links in ZAP to City of New York- § 5-05 Environmental Review Procedures URL

---

README.md
client/app/components/packages/pas-form/project-area.hbs
client/app/components/packages/pas-form/show.hbs
client/app/components/packages/rwcds-form/proposed-project-actions.hbs
client/app/components/packages/rwcds-form/show.hbs

Updated links in pas and rwcds:
- forms
-  show pages Updated readme
Issue #1236

Green fast track updates (merging develop onto qa)

---

client/app/components/packages/projects/projects-new-information.hbs

Add instructional copy to form 
- Closes #1295

1295 Add instructional copy to Applicant Contact form

---

.github/workflows/production.yml
.github/workflows/qa.yml
.github/workflows/staging.yml

Manually install heroku-cli
closes #1339

Upgrade github action runner environment

---

client/app/templates/application.hbs
netlify.toml

Merges phishing banner to master for production release.

Merge phishing warning banner to master

---

client/app/templates/application.hbs

Merging phishing warning banner change to master for release.

Merging phishing warning banner change to master

---

.github/workflows/production.yml
.github/workflows/qa.yml
.github/workflows/staging.yml
client/app/controllers/application.js
client/app/templates/application.hbs
client/config/environment.js

Add phishing warning to banner
closes #1345

Phishing warning

---

.github/workflows/production.yml

Add missing line continuation slash

Fix production workflow typo

---

client/app/components/packages/draft-eas/attached-documents.hbs
client/app/components/packages/equitable-development-reporting.hbs
client/app/components/packages/filed-eas/attached-documents.hbs
client/app/components/packages/pas-form/attached-documents.hbs
client/app/components/packages/rwcds-form/attached-documents.hbs
client/app/components/packages/scope-of-work-draft/attached-documents.hbs
client/app/components/projects/projects-new-attached-documents.hbs
client/app/templates/projects.hbs

Update link assets to to direct to new web team urls
-Closes #1354

Issue 1354 Update asset links

---

client/app/components/projects/projects-new-project-description.hbs

1. Update copy from:
> Please replace information in the brackets to the best of your ability.
to:
> Use the Applications Reviewed by City Planning to reference action types and abbreviations to replace bracketed text with the appropriate information
2. Attach link to **Applications Reviewed by City Planning** copy
- Closes #1358

Issue 1358 Update Project Brief instructions on New Project Initiation form

---

server/src/auth/auth.service.ts

Sync email addresses when logging in
closes NYCPlanning/ae-private#81

Sync ZAP and NYC ID email addresses

---

client/app/components/packages/equitable-development-reporting.hbs
client/app/components/packages/landuse-form/artifact-documents.hbs
client/app/components/packages/landuse-form/attached-documents.hbs
client/app/components/packages/pas-form/attached-documents.hbs
client/app/templates/invoice.hbs
server/.eslintrc.js

Update links to homepage for its upgrade
closes #1361

Homepage redirects
